### ISSUE TITLE
suggestion: restrictions in filebrowser

### ISSUE THREAD

**Issue by othmar52** [ArturSierzant/OMPD#10]
Hi Artur,
i noticed that i can access all directories on my system via `browser.php`where apache user has access rights.

when i try to play files or dirs that are not within mpd's music dir i get an error:
```
Music Player Daemon error
Error: ACK [50@0] {add} Malformed URI
Command: add "/some/filesystem/path"
```

you should restrict access to `$cfg['media_dir']` per default.
its not that important for me but i just wanted to tell you

**Comment by ArturSierzant** [comment]
I'm going to add a feature that lets to play files from any location (also outside MPD database) - as a stream. I hope I'll manage to do that and then access to all folders will be useful. Otherwise I'll restrict access as you suggest.

**Comment by dseomn** [comment]
The web server has access to files that probably shouldn't be made available, including the O!MPD configuration file with a MySQL password in it. I don't think it's a good idea to let users read any file that the web server can read.

**Comment by ArturSierzant** [comment]
With file browser user can see only audio and image files - other types of files are not visible, so they can't be read by user.

**Comment by othmar52** [comment]
but accessing an url like this is indeed a problem:
`http://[O!MPD]/download.php?action=downloadFile&filepath=[O!MPD-path]/include/config.local.inc.php&mime=audio/mpeg`
the configuration file gets downloaded.

you can even download the download-file itself :)
`http://[O!MPD]/download.php?action=downloadFile&filepath=[O!MPD-path]/download.php&mime=audio/mpeg`

**Comment by ArturSierzant** [comment]
I added new setting `$cfg['allow_access_to_all_files']` in `config.inc.php`: default value is `false` which allows to access only to files in `$cfg['media_dir']`. When set to `true` it allows to browse all folders www server has access to.

**Comment by dseomn** [comment]
When I go to http://[redacted]/ompd/getid3/demos/demo.browse.php?listdirectory=%2F, I can still see the contents of the / directory.
