### ISSUE TITLE
Update stuck at 90% after crash

### ISSUE THREAD

**Issue by bamyasi** [ArturSierzant/OMPD#107]
Stupid me, I have accidentally rebooted my DietPi box while the library scan / database update was still in progress. Now O!MPD update page is stuck with file scan progress bar at 90% and does not respond to any buttons. I have tried clearing browser data but apparently something got broken on the server (DietPi) and I cannot figure out where to look to fix it. Help, please!

**Comment by brendan-pike** [comment]
Hi, in the config area if the main Update item is unavailable you might see the the update line with several period after it, ie. .... put your mouse over them and you may be able to cancel the previous update and perform a new one.

**Comment by bamyasi** [comment]
Hi Artur,

Thank you for instant response!

On Friday, November 15, 2019 12:43:56 AM EST DB Informatics wrote:
> Hi, in the config area if the main Update item is unavailable you might see
> the the update line with several period after it, ie. .... put your mouse
> over them and you may be able to cancel the previous update and perform a
> new one.

It worked! Now, this is what I call a perfect Easter egg :-) I would never 
figure it out myself, without your hint.

Have a nice weekend!

--Ivan
