### ISSUE TITLE
Radio Station

### ISSUE THREAD

**Issue by marcbth** [ArturSierzant/OMPD#112]
Hello Artur,
you can integrate the following for the radio:

Library - Now Playling- Favorites- Tidal - Radio

where the radio stations are displayed with cover?

There are some difficulties, because it has to be entered into the database in advance or hard encoded.

I know, it is quite a lot to ask.

Cliff

**Comment by marcbth** [comment]
i can in 'Now Playin' add

http://www.ndr.de/resources/metadaten/audio/m3u/ndrloop19.m3u

because i can not save as radio

many thanks

**Comment by ArturSierzant** [comment]
I think I'll deal with radio now. I'd like to base it on https://fmstream.org/ (and html parser) - or maybe you know any other free radio services?

**Comment by marcbth** [comment]
that sounds good.

I didn't know fmstream.org.

I have a long list of stations for upmpdcli that also broadcast in hd.
especially in the jazz area there is a lot.
the possibility to add your own would be perfect.

do you have the streaming service highresaudio in poland? would try (see tidal) to integrate it. Api is available and a first python script (still from upmpdcli)

Cliff

**Comment by ArturSierzant** [comment]
Sorry, I don't know any HiRes service in Poland - I rarely listen to internet radio...
BTW: in what way do you use internet radio? Do you search addresses on the Internet? And then you save them (in Favorite)? Please write how you image support for radio in O!MPD. 

Regards,
Artur

**Comment by marcbth** [comment]
for the db

CREATE TABLE cfg_radio (id INTEGER PRIMARY KEY, station CHAR (128), name CHAR (128), type CHAR (8), logo CHAR (128));

**Comment by marcbth** [comment]
look at https://github.com/moode-player

**Comment by marcbth** [comment]
https://github.com/florianheinemann/MPD.FM

**Comment by ArturSierzant** [comment]
Radio added in commit e8ce11c9

**Comment by brendan-pike** [comment]
Thanks Artur, I'm quite late to the party as I hadn't updated for sometime.  I was excited to see radio support.
For me however this feature is not working, I get "Error in connection to the Radio Browser server." 
Is there any dependencies I need to be aware of?

**Comment by ArturSierzant** [comment]
CURL extension is needed - but you probably already have it installed (this is checked every time any page is opened). 
Before O!MPD connects to radio-browser servers it checks which one is active. It is done in `initRadioBrowser()` function in `library.inc.php` file. You can try to set this server manually: add line like
` $server = 'https://de2.api.radio-browser.info';`
right before
`  $browser = new AdinanCenci\RadioBrowser\RadioBrowser($server);`
in this function.
Other servers can be:
`fi1.api.radio-browser.info`
`de1.api.radio-browser.info`
Active servers can be found at https://api.radio-browser.info/net
Unfortunately there are moments when none of the servers is online. Anyway please try the above way and let me know if it works.

**Comment by brendan-pike** [comment]
Thanks Artur,  I'll test that further soon but when I visit in Firefox I get this:
`Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://de2.api.radio-browser.info/json/servers. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing). Status code: 502.
`
So I wonder if the CORS issue is related to OMPD

*update: I did some testing and your idea of adding a manual line worked, but ONLY when I use http:// not https://
Could this be related to the overall issue?

**Comment by ArturSierzant** [comment]
I asked Gemini about this error and among other info I received this:

> The fact that you're getting both a CORS error and a 502 status code suggests two potential, possibly related, problems:
> 
> - The server is misconfigured or down: The 502 error strongly suggests that de2.api.radio-browser.info is not functioning correctly. If the server isn't able to process the request properly, it won't be able to send the correct CORS headers either.
> 
> - CORS is not configured (even if the server was up): Even if the server were perfectly healthy, if it's not configured to send the Access-Control-Allow-Origin header for your specific origin, you would still get a CORS error. However, the 502 makes this less of a primary focus for you to fix on your end, as the server itself is having issues.

So maybe it was an issue with radio-browser servers? I also use Firefox (140.0.4, 64-bit) and didn't notice this error. Do you have similar info when using other web browsers?

If `http` works for you, you can try this: remove line
`$server = 'https://de2.api.radio-browser.info';`
and replace
`$url = $server;`
with this:
`$url = 'http://' . $server;`
at the beginning of `initRadioBrowser()` function.
