### ISSUE TITLE
Adding radiostation url as Favorite stream converts url to all lowercase disabling stream...

### ISSUE THREAD

**Issue by maartenlangeveld** [ArturSierzant/OMPD#114]
When adding a radiostation's stream as favorite the url gets converted to lower case which makes the url invalid.

E.G. adding 
`http://thesoundofjazz.net:8000/TheSoundOfJazzHD`
results in
`http://thesoundofjazz.net:8000/thesoundofjazzhd`

The last url is invalid and won't play.

**Comment by ArturSierzant** [comment]
Thanks for notice this - it's fixed in  10463a3.

Regards,
Artur
