### ISSUE TITLE
What kind of work

### ISSUE THREAD

**Issue by marcbth** [ArturSierzant/OMPD#117]
Hi, Artur,

thank you very much for your work.

had me worried.

try to integrate a filemanager (https://github.com/misterunknown/ifm) and update via git (makes it a little easier).

have a new skin (dark), because i like to provide. on the iPad you can see all the information on now playing.

if i can help in any way, please let me know. my offer for the odroid h2 still stands.

Cliff

![IMG_0032](https://user-images.githubusercontent.com/23519079/73742436-bbad3a00-474c-11ea-8818-165c90dfaff9.jpg)
![IMG_0033](https://user-images.githubusercontent.com/23519079/73742437-bbad3a00-474c-11ea-84dd-5532eb41e20a.jpg)

**Comment by ArturSierzant** [comment]
Thanks for your offer - it's very kind of you. I already have 3 RasPi, so no need for next SBC (and no time to play with it...)

Regards,
Artur

**Comment by ArturSierzant** [comment]
I added your skin in b8e7983 - slightly modified: on Library page `Albums not played for more than 3 months` and `Recently played albums` are now full-wide. I also modified `about.txt` and pointed you as the author of that skin.

Thank you very much for contribution.

**Comment by marcbth** [comment]
Hi  Artur,

thank you very much for taking up my work.

can you still change "marcbth" in my handle?

Cliff Baier

**Comment by ArturSierzant** [comment]
Yes, of course. Please just write what would you like me to place in this file.

**Comment by marcbth** [comment]
Hi, Artur,

please write Cliff Baier instead of marcbth.

How's highresaudio? I would like to help you, but i'm not so good with the sql instructions or where. it would extend the code. i already started with it on my fork. hope it helps you.

Cliff

**Comment by ArturSierzant** [comment]
Done. 
I took a brief look at API description - looks promising. First I'll try to write PHP API to communicate with highresaudio, then I'll try to implement it into O!MPD,
But first I'll publish O!MPD v1.06 - I think it's mature enough to do this. Then I'll deal with highresaudio.

Regards,
Artur
