### ISSUE TITLE
Suggestion: Enhancement? Just a little idea ;o)

### ISSUE THREAD

**Issue by virse** [ArturSierzant/OMPD#12]
Hi Artur,

I'm still loving and using OMPD! as my _"Jukebox"_. Maybe you are open for
an enhancement of your great work?

I am using OMPD! with two players. One is the _"normal player as a
jukebox"_ playing the music via soundcard to my amplifier. The second one
is my _"Website-Player"_ where I play the music in a browser application.
Therefore I use two instances of mpd - one as the _"jukebox instance"_ and
the other (with a different port) as the "website instance" with the URL
`http://192.xx.xx.xx:8000/stream.mp3`.

So I modified the playlist.php-file to implement this lines (in the line
of play, stop, random, repeat and so on):

 ```
<div class="playlist_button"><div class="playlist_status_off">
        <i class="fa fa-play sign-ctrl"></i><a
href="http://192.xx.xx.xx:8000/stream.mp3" target="_blank"><small>
(Browserfenster)</small></a>
    </div></div>
```
It is not sexy at all but it opens a new browser window so that I can
hear the music with my browser. Maybe you have a more _"sexy code"_ to
implement that feature? Maybe that a little windows pops up with the
song information and the possibility to stop the music, skip to the next
song and so on.

Perhaps this is a little enhancement you can think about to implement?

Thx again for your awesome work with OMPD!

mike

**Comment by ArturSierzant** [comment]
Hi,
what you can do is install mpd on your all-day computer: just install and make it run, you don't need to configure its music library (i.e. this mpd doesn't need access to your music library, but must be able to play streams). Then add this mpd to your O!MPD. Open O!MPD page and select your new mpd as active player. Now you can play any song from your collection: O!MPD will send to mpd command to play a stream with selected song/album. 'Now Playing' looks and works in this case in normal way: you see all of the information about song, also cover is displayed, even when you click 'file details' you'll see info about it. The only disadvantage is that you can't seek track - when you try to do it, track will be played from the beginning.

I use this feature to play music on my smartphone - in this case playing streams is even more convenient: mpd on smartphone doesn't have to index all of my music library.

This feature has been available in GitHub version of O!MPD since a few days, so if you use older version please try new one.

I hope this will help. 

Best regards,
Artur

**Comment by virse** [comment]
Thx a lot.
Hm, to install mpd on my all-day machine could be a solution.
I will see if i can Figure it out how to implement the features i
mentioned.
Greezs

Sent from Nine[1]

-------------------------
VON: Artur Sierżant <notifications@github.com>
GESENDET: 05.12.2016 8:32 nachm.
AN: OMPD@noreply.github.com
CC: virse; Author
BETREFF: Re: [ArturSierzant/OMPD] Suggestion: Enhancement? Just a little
idea ;o) (#12)

> Hi,
> what you can do is install mpd on your all-day computer: just install
> and make it run, you don't need to configure its music library (i.e.
> this mpd doesn't need access to your music library, but must be able to
> play streams). Then add this mpd to your O!MPD. Open O!MPD page and
> select your new mpd as active player. Now you can play any song from
> your collection: O!MPD will send to mpd command to play a stream with
> selected song/album. 'Now Playing' looks and works in this case in
> normal way: you see all of the information about song, also cover is
> displayed, even when you click 'file details' you'll see info about it.
> The only disadvantage is that you can't seek track - when you try to do
> it, track will be played from the beginning.
>
> I use this feature to play music on my smartphone - in this case playing
> streams is even more convenient: mpd on smartphone doesn't have to index
> all of my music library.
>
> This feature has been available in GitHub version of O!MPD since a few
> days, so if you use older version please try new one.
>
> I hope this will help.
>
> Best regards,
> Artur
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub[2], or mute the
thread[3].
>
>
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/ArturSierzant/OMPD","title":"ArturSierzant/OMPD","subtitle":"GitHub
repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open
in
GitHub","url":"https://github.com/ArturSierzant/OMPD"}},"updates":{"snippets":[{"icon":"PERSON","message":"@ArturSierzant
in #12: Hi,\r\nwhat you can do is install mpd on your all-day computer:
just install and make it run, you don't need to configure its music library
(i.e. this mpd doesn't need access to your music library, but must be able
to play streams). Then add this mpd to your O!MPD. Open O!MPD page and
select your new mpd as active player. Now you can play any song from your
collection: O!MPD will send to mpd command to play a stream with selected
song/album. 'Now Playing' looks and works in this case in normal way: you
see all of the information about song, also cover is displayed, even when
you click 'file details' you'll see info about it. The only disadvantage is
that you can't seek track - when you try to do it, track will be played
from the beginning.\r\n\r\nI use this feature to play music on my
smartphone - in this case playing streams is even more convenient: mpd on
smartphone doesn't have to index all of my music library.\r\n\r\nThis
feature has been available in GitHub version of O!MPD since a few days, so
if you use older version please try new one.\r\n\r\nI hope this will help.
\r\n\r\nBest regards,\r\nArtur"}],"action":{"name":"View
>
Issue","url":"https://github.com/ArturSierzant/OMPD/issues/12#issuecomment-264952318"}}}



Links:
------
[1] http://www.9folders.com/
[2] https://github.com/ArturSierzant/OMPD/issues/12#issuecomment-264952318
[3]

**Comment by virse** [comment]
Hi Artur,

thx again for your tip. I was able to config the mpd on my all-day computer and I enjoy OMPD/my music library right know while I'm writing this lines.

Awesome!

Greets Michael
