### ISSUE TITLE
Tidal Favorites in Now Playing 

### ISSUE THREAD

**Issue by marcbth** [ArturSierzant/OMPD#120]
Hi, Artur,

which I noticed:

as soon as I import my favorites from Tidal Favorite into now playing, I have two errors.

1. no album pictures are displayed and no information.

See pictures.

Will it actually be possible to create or save my own favorites (Tidal Playlist)?

![IMG_0042](https://user-images.githubusercontent.com/23519079/74604531-38ca9e80-50bf-11ea-9f92-131f5d968b45.jpg)
![IMG_0041](https://user-images.githubusercontent.com/23519079/74604532-39fbcb80-50bf-11ea-9dda-2d719229160f.jpg)

Cliff

**Comment by ArturSierzant** [comment]
I couldn't reproduce it, but changed one thing in 5c97516 - please check if this helped.
As for saving/creating Tidal playlists - I don't plan to do this. Instead of this one can add Tidal (and also YouTube) tracks to O!MPD playlists (Favorites).

**Comment by marcbth** [comment]
Hi, Artur,

thank you for your trouble. But the result is the same.

No change in the display.

Unfortunately.

Cliff

**Comment by marcbth** [comment]
Hello Artur

would you like to be mentioned in http://www.highfidelity.pl?

hifistatement.net makes a report about my music server, where
i have integrated my fork (different skin, add poweroff/reboot, server settings) from ompd.

Cliff

**Comment by ArturSierzant** [comment]
I think I found the problem - fixed it in 3ecb0a1. I was able to reproduce this issue on latest version of DietPi. Please check, if it helped also in your case.

It would be nice to be mentioned in highfidelity.pl - I hope it would be in positive way :) Do you know Mr Wojciech Pacuła? In Poland he is well-known audio journalist (although his opinions are in some cases controversial). 

Will hifistatement.net write about your server? Do you know when? I'd like to read this article. 
Is this server you are offering made by you, I mean did you put some devices into a case? Could you show some pictures? It's very interesting...

Regards,
Artur

**Comment by marcbth** [comment]
Hi, Artur,

Pictures I send you by private email.

Test will be online next week.

I don't know the journalist but the head of hifistatement (dirk sommer) they have a collaboration.

tidal is running perfectly now

Cliff
