### ISSUE TITLE
Integrate Highresaudio

### ISSUE THREAD

**Issue by marcbth** [ArturSierzant/OMPD#121]
Hi, Artur,

I just spoke with Lothar from highresaudio and he would be very happy if highresaudio could be integrated into ompd in addition to tidal.

I have API and would be happy to send it to you with an access. The service is also available in poland.

I'm already in the process of expanding ompd source code for highesaudio, so you don't have too much work.

https://www.highresaudio.com/en/site/home

see my fork

Cliff

**Comment by marcbth** [comment]
Hi, Artur,

are you making any progress with integration?

Cliff

**Comment by ArturSierzant** [comment]
Sorry, nothing yet...

**Comment by marcbth** [comment]
is there anything I can do to help?

**Comment by ArturSierzant** [comment]
No, thanks - just don't have enough free time now...

**Comment by marcbth** [comment]
Hi, Artur,

Thank you for the integration of HRA. Sounds really good in comparison.

Hope you're okay.

Is there a way to add the categories (Tidal,HRA new etc?)?

Send you the new access data by mail.

Cliff

**Comment by ArturSierzant** [comment]
For HRA this could be possible - their API allows to list e.g. new releases. For Tidal it is a problem - I don't have access to original API, all that's working is from reverse engineering. I'll try to figure something out, but this can be not that easy...

Anyway,  next I'll try to add possibility to add tracks from HRA to O!MPD's playlists (Favorite) and add support to user playlists from HRA.

**Comment by marcbth** [comment]
Hi, Artur,

thank you very much for your work.

trying to make a deal with tidal and qobuz to use the API.

HRA sounds a lot better.

Did you get a little further with the menu structure and the playlist of hra?

Cliff

**Comment by ArturSierzant** [comment]
Having access to Tidal or Qobuz API would be great! 
Unfortunately the HRA demo account you sent me expired, so I can't do anything now...

**Comment by ArturSierzant** [comment]
Hi Cliff,

I've done some further integrations with HRA - new albums on main Library page and dedicated HRA subpage with new albums of some genres.

Hope you are doing ok in this hard times.

Regards,
Artur

**Comment by ArturSierzant** [comment]
Basic (and even more) integration is done so I'm closing this issue.
