### ISSUE TITLE
Login issue just appeared

### ISSUE THREAD

**Issue by owl770** [ArturSierzant/OMPD#122]
Hi - I have been using O!MPD for a number of years and really like it.
I normally launch O!MPD in an iframe from another locally hosted webpage. The index file contains the line:
`<iframe src="http://myhost.local/ompd/playlist.php" width=100% height=950></iframe>`
This has worked fine for more than a year, then suddenly I cannot log into O!MPD. I get the error:
![image](https://user-images.githubusercontent.com/16440359/77241230-32da5700-6c43-11ea-90eb-eada98606363.png)
If I type `http://myhost.local/ompd/playlist.php` directly into my browser's address bar, it works as expected.
I have tried upgrading to the latest O!MPD from github and also clearing all cookies from my browser but still have the login issue. I have also tried multiple browsers and multiple laptops. All have the same problem.
I am assuming that the issue is at my end and not with O!MPD but I am not sure how to go about debugging the issue. Does anyone have any ideas or suggestions?

**Comment by ArturSierzant** [comment]
Hi, 
you can try to remove all data from table `session` in DB, then remove cookies and try to log in again.

Best regards,
Artur

**Comment by owl770** [comment]
Thanks for the suggestion - deleted all records from session table, cleared browser cookie cache but still no change. Loading in an iframe gets the error but loading the page directly works OK.

**Comment by owl770** [comment]
A little bit of debugging has found out that in `json.php` in the `loginStage1` function, when the page is loaded directly, the sid is retrieved successfully but when the page is loaded in an iframe, the sid is empty. Not sure if this helps anyone.

**Comment by owl770** [comment]
A bit more digging has found this...
`https://blog.heroku.com/chrome-changes-samesite-cookie`
Does this sound like it is the same issue? Can it be fixed? Thanks.

**Comment by ArturSierzant** [comment]
Try this: in `include/initialize.inc.php` find around line 252:
```
if (!$sid) {
		$sid = randomKey();
		header('Set-Cookie: netjukebox_sid = ' . $sid . '; Path=/; Max-Age = 31536000; samesite=strict');
		//logoutSession();
	}
```
and replace it with:
```
if (!$sid) {
		$sidTmp = randomKey();
		header('Set-Cookie: netjukebox_sid = ' . $sidTmp . '; Path=/; Max-Age = 31536000; samesite=strict');
		$sid 			= cookie('netjukebox_sid');
		if (!$sid) {
			?>
			<script>
			document.cookie = 'netjukebox_sid=<?php echo($sidTmp); ?>; Max-Age = 31536000';
			</script>
			<?php
		}
		$sid = $sidTmp;
	}
```
Then make sure you have only one active session to O!MPD from your browser (only page with `iframe` is open), reload page, delete cookies and try to login. After first attempt you probably will see `Login fail` info - click on `Login` and try to login again. This time you should succeed.
If this works in your case, I'll test it in other scenarios and finally add to code. 

Regards,
Artur

**Comment by owl770** [comment]
Thanks @ArturSierzant for the changes.
It now works in Safari (13.0.5) but still doesn't work in Chrome (80.0.3987.149).
It appears that in Safari, the cookie gets created:
`netjukebox_sid	I4im0pvUd9fZX5XFSfdhG5xKfT3Qde_4nsswv699	musicpi2.local	/ompd	24/03/2021, 7:47:21 pm	54 B			`
but it doesn't get created in Chrome.

**Comment by ArturSierzant** [comment]
What OS do you have on machine with Chrome? I use Win7 with Chrome 80.0.3987.149 (64-bit) and cookie is created. On the other comp with Win10 it also works (but here I can't check now what version of Chrome is there). I have some other ideas how to fix it, so there still is a hope :)

**Comment by owl770** [comment]
I'm using MacOS 10.14.6 - interesting that the same version works differently on Win7.

**Comment by ArturSierzant** [comment]
Strange, indeed... Since it didn't help in your case, I have another approach. First revert changes in `include/initialize.inc.php`. Next replace `javascript-src/initialize.js` with the one attached to this message and try to login (procedure as above)

[initialize.zip](https://github.com/ArturSierzant/OMPD/files/4376417/initialize.zip)

**Comment by owl770** [comment]
Thanks for your patience. Still no go in Chrome in the iframe. Still OK in Safari. Still OK in Chrome outside of the iframe.
In Chrome, inside an iframe:
1) The netjukebox_sid cookie gets created with the first login window
2) Click login and see the "O!MPD requires cookies to login message"
3) Console show a POST error of:
VM637 cache.php:224 POST http://myhost.local/ompd/json.php?ajax=1 500 (Internal Server Error)
ajaxRequest @ VM637 cache.php:224
loginStage1 @ playlist.php:856
onsubmit @ playlist.php:873
4) Click login and get the login window
5) Click login and see the "O!MPD requires cookies to login message"
6) Console show a POST error of:
VM901 cache.php:224 POST http://myhost.local/ompd/json.php?ajax=1 500 (Internal Server Error)
ajaxRequest @ VM901 cache.php:224
loginStage1 @ index.php?tileSizePHP=193:861
onsubmit @ index.php?tileSizePHP=193:878

**Comment by ArturSierzant** [comment]
OK, looks like we are one step further - cookie is created. The problem is that I can't reproduce this error on my system, so it's hard to find the reason. But I've found another place, where changes may help - in ma case it helped for double-login with 'Login fail' message: now login goes in one step, without error message. Try this, maybe it will also help in your case:
1. in `include/initialize.inc.php` in function `logoutSession()` find line 595:
```
header('Set-Cookie: netjukebox_sid = ' . $sid . '; Path=/; Max-Age = 31536000; samesite=strict');
```
2. after this line pase this:
```
?>
<script>
document.cookie = 'netjukebox_sid=<?php echo $sid; ?>; Max-Age = 31536000';
</script>
<?php
``` 
3. delete cookies, try to login

**Comment by owl770** [comment]
Sorry for stuffing you around but I made a procedural error. The cookie is NOT being created. In my last post, the cookie was created by another testing session. Sorry.

Not sure if I was explicit enough in the beginning. I access a webpage on host1 (RPi running raspbian stretch) which contains an iframe with a src that points to host2 (RPi running raspbian stretch). If I access host2 directly, all works OK. It is the fact that host1 is trying to get to the cookie from host2 that is the issue.

The html from **host1** is:
`<iframe src="http://host2.local/ompd/playlist.php" width=100% height=950></iframe>`

I have confirmed that the issue exists on a Win7 system (running as a VM on my Mac in VirtualBox) using Chrome. Login fails and no cookies are created.

I have noticed that using Safari (which works), the netjukebox_sid cookie is created with samesite NOT set and path=/ompd. When I use Mac Chrome and access host2 directly (which works), the netjukebox_sid cookie is created with samesite=Strict and path=/. When I access host2 via host1, the cookies are not created.

Thanks for your patience.

**Comment by owl770** [comment]
Just discovered that this now works on one Mac laptop but not mine.
@ArturSierzant please don't waste anymore time on this until I investigate further.
Thanks again for all your help so far.

**Comment by owl770** [comment]
Another piece to the puzzle...although both laptops run the same version of Chrome, the working one is on macOS 10.13.6 and the non-working one is on macOS 10.14.6...

**Comment by ArturSierzant** [comment]
Yes, you made it clear enough. For all my testing I've been using static html page:
```
<html>
<body>
<iframe src="http://192.168.1.120/ompd/playlist.php" width=100% height=100%></iframe>
</body>
</html>
``` 
placed on my laptop with Win10. O!MPD runs on RasPi (192.168.1.120).

OK, so I'll wait for results of your investigation.

May I know why you use iframe instead of direct call to web server?

**Comment by owl770** [comment]
Hi - I use an iframe because it is part of a group of pages that I have to monitor various things about the house.
My index.html file in the web root directory is like:

`<!DOCTYPE html>`
`<html>`
`<head>`
`<link rel="shortcut icon" href="images/favicon.ico">`
`<link href="/static/style.css" rel="stylesheet" type="text/css" />`
`<title>Welcome to XXX</title>`
`</head>`
`<body>`
`<h1>Welcome to XXX</h1>`

`<ul>`
`  <li><a class="nav" href="/ompd" target="main_iframe">Music</a></li>`
`  <li><a class="nav" href="/nagios" target="main_iframe">Status</a></li>`
`  <li><a class="nav" href="/stats" target="main_iframe">Statistics</a></li>`
`  <li><a class="nav" href="/cctv" target="main_iframe">Cameras</a></li>`
`  <li><a class="nav" href="/automation" target="main_iframe">Automation</a></li>`
`</ul>`
`<br><br><br>`
`<iframe src="/ompd/index.php" name="main_iframe" style="border:none" width="100%" height="1500"></iframe>`

`</body>`
`</html>`

Each of the buttons displays a different page in the iframe ("main_iframe").

**Comment by ArturSierzant** [comment]
If that's not a problem from any other reasons, you can try to put this file on www server where O!MPD runs. Then you could call it like this:
`http://host2.local/ompd/index.html`
or 
`http://host2.local/index.html`
I think that this way problem with cookies would be solved.

**Comment by owl770** [comment]
@ArturSierzant what a brilliant, elegant and simple solution to a complex problem.
Suits my environment completely (I understand it may not suit others but..).
Implemented and now the issue is sorted!!!
Thanks for the suggestion.
Issue closed (for me).

**Comment by ArturSierzant** [comment]
I'm glad I could help :)

Best regards,
Artur
