### ISSUE TITLE
add aiff and dff in config.inc.php

### ISSUE THREAD

**Issue by marcbth** [ArturSierzant/OMPD#124]
Hi, Artur,

please add aiff and dff to the config.inc.php

in case of an update it might make a mistake with dff but it plays it over files.

$cfg['media_extension'][] = 'dff';
$cfg['media_extension'][] = 'aiff';

One more question, is it possible to display the albums or artists (A, B ...) alphabetically in the library view (as default) and not after the last update as it is now.

Thanks for your effort.

Cliff

**Comment by ArturSierzant** [comment]
Hi Cliff,
`aiff` is supported by getID3 and I think it can be added. But `dff` is not supported by getID3, so O!MPD would not be able to read tags from that kind of file. Have you try it?

**Comment by marcbth** [comment]
Hi, Artur,

when i write it in the config.inc.php and then do an update, i probably get an error with dff files. 
But I can play them if I go to "files". 

For me this is enough.

Just sent you a private mail.!

Many greetings

Cliff

**Comment by marcbth** [comment]
Hello Artur,
i had contact with James Heinrich from getid3 yesterday and he added support for dff files in getid3 yesterday. 

https://github.com/JamesHeinrich/getID3/commit/cde8ac014c7d8fce9af004974eff400a9ee348a6

solved another problem.

Oh yes, at the moment the tidal search shows almost no cover.

Cliff

**Comment by ArturSierzant** [comment]
I added `aiff` and `dff` extensions to `config.inc.php` and updated `getid3` - thanks for reporting this. I also fixed problem with Tidal covers.

Regards,
Artur

**Comment by marcbth** [comment]
Hi Artur, 
Many thanks for the fast processing.

Hope you have less stress now.

Cliff
