### ISSUE TITLE
Adding MQA quality to Tidal API

### ISSUE THREAD

**Issue by paradix** [ArturSierzant/OMPD#135]
Maybe it could be possible to add Master quality to Tidal streaming.
Have a look at https://github.com/Dniel97/RedSea

**Comment by ArturSierzant** [comment]
That's interesting - especially login with oauth2. I'll take a look at this - thanks.

**Comment by paradix** [comment]
Would be nice to see that in OMPD! as it work great with RedSea when using the FireTV auth method.
And many thanks for the Tidal views @ArturSierzant great work.

**Comment by ArturSierzant** [comment]
I've found a better way of showing Tidal views - with data like 'Suggested Albums for You', etc. Hope to update soon.

**Comment by paradix** [comment]
I think this issue can be closed now. 
Playing MQA with my HiFi subscription seems to work as expected 

![MQA](https://user-images.githubusercontent.com/3265277/116228075-1ddccb00-a755-11eb-99c1-e40ec7080ee9.jpg)

**Comment by ArturSierzant** [comment]
This must be side-effect of OAuth2 and capabilities of device used to get auth (Fire Stick HD). Thanks for reporting this - I don't have MQA compatible DAC, so I couldn't check it myself. In my case MQA files are played back by MPD as 24bit-44.1/48kHz (at least the ones I tried).

**Comment by paradix** [comment]
> In my case MQA files are played back by MPD as 24bit-44.1/48kHz (at least the ones I tried).

That is standard behavior with MQA playing on a DAC with no support. 

I'm glad it works, lets hope Tidal keeps it that way ;)
