### ISSUE TITLE
Advanced comment fields

### ISSUE THREAD

**Issue by brendan-pike** [ArturSierzant/OMPD#138]
Using Picard for tagging and have the classical plugin enabled, I've noticed comment fields are now becoming an array, 
For example, this is for comment:artists_options
`{'Classical Extras': {'Artists options': {'run extra artists': True, 'orchestra strings': 'orchestra, philharmonic, philharmonica, philharmoniker, musicians, academy, symphony, orkester', 'choir strings': 'choir, choir vocals, chorus, singers, domchors, domspatzen, koor, kammerkoor', 'group strings': 'ensemble, band, group, trio, quartet, quintet, sextet, septet, octet, chamber, consort, players, les ,the , quartett', 'replace artist name with alias?': 'replace', 'alias vs credited-as': 'alias over-rides', 'use recording artist': False, 'recording artist name style': 'performer', 'disallow blank recording artist': False, 'recording artist effect on track artist': 'merge', 'Album prefix': True, 'include arrangers': True, 'exclude lyricists if no vocals': True, 'fix cyrillic': True, 'use release credited-as name': True, 'use release relationship credited-as name': True, 'use release-group credited-as name': True, 'use recording credited-as name': False, 'use recording relationship credited-as name': True, 'use track credited-as name': True, 'use credited-as name for performer': True, 'use credited-as name for composer': False, 'use credited instrument': True, 'exclude solo': True, 'chorusmaster': 'choirmaster', 'orchestrator': 'orch.', 'concertmaster': 'leader', 'lyricist': 'lyrics', 'librettist': 'libretto', 'writer': 'writer', 'arranger': 'arr.', 'reconstructed by': 'reconstructed', 'revised by': 'revised', 'translator': 'trans.', 'split lyrics': True, 'lyrics': 'lyrics', 'album lyrics': 'albumnotes', 'track lyrics': 'tracknotes', 'Tags to blank': 'artist, artistsort', 'Tags to blank 2': 'performer:orchestra, performer:choir, performer:choir vocals', 'File tags to keep': '', 'Clear previous tags': False, 'populate sort tags': True, 'standardize artists': False, 'translate artist names': False, 'line 1': {'source': 'album_soloists, album_ensembles, album_conductors', 'tag': 'artist, artists', 'conditional': False}, 'line 2': {'source': 'recording_artists', 'tag': 'artist, artists', 'conditional': True}, 'line 3': {'source': 'soloist_names, ensemble_names, conductors', 'tag': 'artist, artists', 'conditional': True}, 'line 4': {'source': 'soloists', 'tag': 'soloists, trackartist, involved people', 'conditional': False}, 'line 5': {'source': 'release', 'tag': 'release_name', 'conditional': False}, 'line 6': {'source': 'ensemble_names', 'tag': 'band', 'conditional': False}, 'line 7': {'source': 'composers', 'tag': 'artist', 'conditional': True}, 'line 8': {'source': 'MB_artists', 'tag': 'composer', 'conditional': True}, 'line 9': {'source': 'arranger', 'tag': 'composer', 'conditional': True}, 'line 10': {'source': '', 'tag': '', 'conditional': False}, 'line 11': {'source': '', 'tag': '', 'conditional': False}, 'line 12': {'source': '', 'tag': '', 'conditional': False}, 'line 13': {'source': '', 'tag': '', 'conditional': False}, 'line 14': {'source': '', 'tag': '', 'conditional': False}, 'line 15': {'source': '', 'tag': '', 'conditional': False}, 'line 16': {'source': '', 'tag': '', 'conditional': False}}}}`

Currently OMPD just displays as is.  
Thoughts?

**Comment by ArturSierzant** [comment]
I fixed it in commit 5b7d349. Now all `COMMENT` entries that contain string `{'Classical Extras': {` are ignored.
Hope that helps.

Thanks for reporting this.

Regards,
Artur
