### ISSUE TITLE
Error in connection to Tidal (Client not found).

### ISSUE THREAD

**Issue by marcbth** [ArturSierzant/OMPD#139]
hello Artur,

I hope you are well and healthy despite the crisis.

since today this error message appears:

Error in connection to Tidal (Client not found).

Tidal as an app or weblogin works.

can you help?

Cliff

**Comment by ArturSierzant** [comment]
Thanks, I'm doing well, I hope you're too.

I've also noticed this issue today - looks like Tidal banned another token. I've got one more that works - it's from iOS, so it serves ALAC (still lossless) files, not FLAC. Unfortunately it's the last working token I know. I'm sending this to you on priv.

oauth2 is the only right option... I'll have to speed up (actually start) work on it.

Regards
Artur

**Comment by marcbth** [comment]
Many Thanks
