### ISSUE TITLE
[QUESTION] about configuration name_source

### ISSUE THREAD

**Issue by othmar52** [ArturSierzant/OMPD#14]
Hi Artur,
I spotted a lot conditions like
``` php
if ($cfg['name_source'] != 'tags') 
if ($cfg['name_source'] == 'tags')
```
so i tried to figure out what happens if i `$cfg['name_source'] = 'foo';` which resulted in a fatal error.
``` php
//  +------------------------------------------------------------------------+
//  | Source of artist/album title/track title                               |
//  +------------------------------------------------------------------------+
//  | 'tags' - data from tags in file                                        |
//  | Others values are not allowed now - don't change this setting or update|
//  | of library will crash. This is for future use.                         |
//  +------------------------------------------------------------------------+
$cfg['name_source']						= 'tags';
```
what are your plans with that? shouldn't this code get removed?

**Comment by ArturSierzant** [comment]
Hi,
maybe in the future I'll use it for getting data (like artist, album, title, etc.) from files/folders names (like in Netjukebox) as an alternative for tags. The code used when $cfg['name_source'] != 'tags' is mostly residue after Netjukeox.

**Comment by othmar52** [comment]
My suggestion:
remove as much dead/unused code as possible!

in case some day you'll continue to implement this, use it only in those helper function of [tagProcesser.inc.php](https://github.com/othmar52/OMPD/blob/4f6bead43a357d8b3a52be3df1038c3c61343ddb/include/tagProcessor.inc.php) by passing the path as an additional argument.

further you would be able to apply this alternative artist/title reading for music files without tags (e.g. *.wav) regardless of any configuration
