### ISSUE TITLE
getID3 causes error as PHP8.0 is more strict on variable type

### ISSUE THREAD

**Issue by Trillien** [ArturSierzant/OMPD#142]
Hi,
I've just installed PHP8.0 and O!MPD lastest version from OMPD repository on GitHub.
As I updated the database, I receive PHP error "Uncaught TypeError: decbin(): Argument #1 ($num) must be of type int, string given" caused by getID3.

Issue has already been solved in getID3 repository: [https://github.com/JamesHeinrich/getID3/issues/299](https://github.com/JamesHeinrich/getID3/issues/299)
Thus, I've replaced OMPD/getid3 folders by current version of getID3 from JamesHeinrich/getID3 repository.

That solves the issue.

**Comment by ArturSierzant** [comment]
Hi,
first of all I'm sorry for late answer - I was away from computer.

Thank you very much for this info - I'll replace getID3 in next commit.

Regards
Artur
