### ISSUE TITLE
Streams to MPD are length zero

### ISSUE THREAD

**Issue by tomchiverton** [ArturSierzant/OMPD#144]
```
Oct 31 15:47 : mad: input/Input does not appear to be a mp3 bit stream
Oct 31 15:47 : ffmpeg/mp3: Format mp3 detected only with low score of 1, misdetection possible!
Oct 31 15:47 : ffmpeg/mp3: Failed to read frame size: Could not seek to 1026.
Oct 31 15:47 : exception: avformat_open_input() failed: Invalid argument
Oct 31 15:47 : exception: Failed to decode http://ompd.house/stream.php?action=streamTo&stream_id=-1&track_id=&ext=.mp3
Oct 31 15:47 : player: played "http://ompd.house/stream.php?action=streamTo&stream_id=-1&track_id=&ext=.mp3"
Oct 31 15:47 : mad: input/Input does not appear to be a mp3 bit stream
```

If I 'wget' this URL by hand. it's zero length

Nothing in Apache error log.

Fresh install today.

**Comment by tomchiverton** [comment]
How can I help debug this ? Can I maybe trigger the file-to-stream action in a debug mode or something ?

**Comment by tomchiverton** [comment]
Argh. This happens if the trailing slash is missing from the media_dir - could we maybe check for this error and put a message up ?

**Comment by ArturSierzant** [comment]
Thanks for investigating and finding problem. I fixed this in commit a5e5839 - please check if that helps.

**Comment by tomchiverton** [comment]
Can probably remove https://github.com/ArturSierzant/OMPD/blob/master/update.php#L70 now too ?

While on the subject, is there a way to update the library from the command line e.g. from Cron ?

**Comment by ArturSierzant** [comment]
Yes, that's right - I remove those lines in next commit.

CLI update is on TODO list - unfortunately it's not possible yet.

Thanks again for your contribution.
