### ISSUE TITLE
PHP8 support fixes missing from release

### ISSUE THREAD

**Issue by tomchiverton** [ArturSierzant/OMPD#145]
https://github.com/ArturSierzant/OMPD/commit/febfd3565e00ec44333ad061c8e3ce2123448c7d (etc) doesn't appear to have made it to the latest release downloaded from the home page @ http://ompd.pl/download-ompd - http://ompd.pl/downloads/ompd/ompd-1.06.zip

I fetched the above, looked in initilize.inc.php and there's no "if" around the checkDefaultFavorites call for instance

I get the exact errors #137 on a newly updated Fedora box with PHP8. 

OMPD was fine before the update.

Could we get a new release published ?

**Comment by ArturSierzant** [comment]
I've been going to publish new version for long time, unfortunately still can't find free time. I'll try to do it in next few days.

**Comment by ArturSierzant** [comment]
Finally I've published new version - thanks for mobilizing :)
