### ISSUE TITLE
Tidal Login error

### ISSUE THREAD

**Issue by marcbth** [ArturSierzant/OMPD#146]
Hello Artur,

since today I have

Login failed. Error:
{"status":401,"error":"invalid_client","sub_status":1005,"error_description":"Client with token aR7gUaTK1ihpXOEP not found"}

can you help please.

Cliff

**Comment by marcbth** [comment]
see this:

https://github.com/yaronzz/Tidal-Media-Downloader/issues/721

**Comment by ArturSierzant** [comment]
Yes, I noticed it yesterday. Problem is that we (O!MPD and other programs) were using for authentication `clientId` and `clientSecret` taken from Fire TV Stick and it was probably banned/changed by Tidal. So we need new working `clientId/clientSecret` pair.

**Comment by marcbth** [comment]
I have a Fire TV Stick

**Comment by Mr-Negative** [comment]
I do not know how to do it with Fire TV stick, but i suspect that is way to do it in few words, and please please please try to do it.
Here is tutorial for this
https://developer.amazon.com/docs/fire-tv/network-proxy.html

**Comment by ArturSierzant** [comment]
@Fokka-Engineering had some clientId/clientSecret (see https://github.com/Fokka-Engineering/TIDAL/wiki/Copyright) so maybe he will help with getting them. 
@marcbth - is Tidal working on your Fire TV?

**Comment by marcbth** [comment]
@Fokka-Engineering

Tidal work on Fire TV with login with another PC

Schöne Grüße nach Düsseldorf.

**Comment by Mr-Negative** [comment]
@marcbth  what you mean another PC, isn't fire tv attached to Screen?

**Comment by marcbth** [comment]
@Mr-Negative i open the tidal app on fire tv and then i must go to link.tidal.com on a pc and enter the code that show on fire tv. tidal works

**Comment by Mr-Negative** [comment]
@marcbth so there is a hope if update didn't also encode stuff. 
Was there update of app on firetv? if not and its working, please try to block autoupdates of apps if its possible. 

Please learn how to proxy and route firetv ->pc as proxy-> servers
and listen to /oauth2/device_authorization for the best (but you will need to logout and login with pc code once again to make this connetion probably) or any of track info grabs and check if they have application/vnd.tidal.bts as manifestMimeType;
