### ISSUE TITLE
Volume Slider

### ISSUE THREAD

**Issue by surtarso** [ArturSierzant/OMPD#148]
Hi there, I've installed 1.06 using the dietpi installer and everything not only runs great but also look exceptional!

the ONE thing I couldnt figure out yet is why I cant change the volume with the browser slider... 
If I ssh to my rpi I can alsamixer and adjust the 3.5mm volume... but not using the slider on the web client... 

This is pretty bad when I want to listen to music late at night =((

I tried checking all scripts and configs to see if I found something out of place but couldnt... 
Im on a raspberry pi (bullseye) using alsamixer and 3.5mm jack

**Comment by marcbth** [comment]
Hi,
It is relatively simple. You have to change the following in Mpd.conf:

nano /etc/mpd.conf


You should have something like this

At device you have to define your output 
Before that just aplay -l

audio_output {
# type "alsa
# name "My ALSA Device"
## device "hw:0,0" # optional
## format "44100:16:2" # optional
## mixer_type "hardware" # optional
## mixer_device "default" # optional
## mixer_control "PCM" # optional
## mixer_index "0" # optional
#} 

you Must change in

mixer_type "software"

And then 

service mpd restart

After that you can change the volume in ompd.

If you have any questions, please contact me 

Cliff

**Comment by surtarso** [comment]
hey thanks! I was looking at ompd confs and not mpd itself, duh! ;)
my aplay -l showed the expected bc2835 from pi hardware, but that didnt work.
After a couple of attempts I scrolled thru the conf and saw at the very bottom the alsa settings dietpi made as default and since they have their own way of doing things, its actually called "DietPi ALSA". 
Working perfectly now, many thanks!

**Comment by marcbth** [comment]
You're welcome. 

Have fun listening to music
