### ISSUE TITLE
Multiple disc identification / grouping

### ISSUE THREAD

**Issue by surtarso** [ArturSierzant/OMPD#152]
What exactly does OMPD expects to see to judge if  its a multidisc album? I have the setting set to manage them, but they still appear as 2 albums in list (expected) but with no indication of what album number is... I have some 10 CD's albums and I just get 10 equal covers (expected) but no way of knowing what CD # they are, even when clicked in. So If I wanted to add them in order to my playlist there would be no way of knowing which one is 1st or last... OMPD sees them all as "other version".

My albums are organized like this:
artist name /   album name (year)   /   CD #   /   #-artist-song

I noticed you specifically say that it will search on "album TITLE" for the cd numbers. So is it expecting:
artist name /   album name (year) CD #   /    #-artist-song ?

I got a big collection (30k+) and wanted to be sure before I batch rename this ;)
they are all properly tagged by muscbrainz btw, if the # info is being pulled from there

$cfg['group_multidisc'] = true; -> also not grouping them... so probably folder naming?

in addition: I added some more "types" of multidiscs that musicbrainz uses in my collection and were not covered by the config:
$cfg['multidisk_indicator'][] = "HDCD ";
$cfg['multidisk_indicator'][] = "12 Vinyl ";
$cfg['multidisk_indicator'][] = "Digital Media ";
$cfg['multidisk_indicator'][] = "Hybrid SACD ";
$cfg['multidisk_indicator'][] = "SHM-CD ";

that didnt help with above issues
So I think I'm doing something wrong about multidiscs coz at this point its pretty hellish to manage them into a playlist

**Comment by surtarso** [comment]
no way of knowing CD#
![Screenshot](https://user-images.githubusercontent.com/54255356/145718610-7f329a70-0b96-46da-bbc9-ee9c35d7a237.png)
file structure
![Screenshot_20211212_123406](https://user-images.githubusercontent.com/54255356/145718781-ceb577cd-246c-4e00-ab43-585a5876899d.png)
search not grouped by album
![Screenshot(1)](https://user-images.githubusercontent.com/54255356/145718897-5550b406-edf7-4902-a003-bb88f9d13093.png)
search not grouped by artist
![Screenshot(2)](https://user-images.githubusercontent.com/54255356/145718976-72c94045-46f9-4a78-b4f0-fc7ce9a8415e.png)

**Comment by ArturSierzant** [comment]
Your folders are OK - actually O!MPD doesn't care about folders name (each folder is treated as album - with small exceptions). The most important for grouping and 'other versions' is value of ALBUM tag. In your case try to add to ALBUM string "Hybrid SACD " with consecutive number, i.e "Infinite Box Set Hybrid SACD 01", "Infinite Box Set Hybrid SACD 02", etc.
Example from my collection: I have 2 versions of Genesis' album 'The Lamb Lies Down On Broadway', each of them consists of 2 discs. They have ALBUM as follows:
The Lamb Lies Down On Broadway (2007 Remaster, 24bit-88.2kHz, Disc 1)
The Lamb Lies Down On Broadway (2007 Remaster, 24bit-88.2kHz, Disc 2)
The Lamb Lies Down On Broadway, Disc 1
The Lamb Lies Down On Broadway, Disc 2

In config I have:
`$cfg['multidisk_indicator'][] = "Disc ";`

In search results they appear as 4 single discs:

![obraz](https://user-images.githubusercontent.com/22481059/145866935-623e9fb0-5d40-4912-ab00-ebbf401b6f04.png)

But in list of albums they are grouped into one:

![obraz](https://user-images.githubusercontent.com/22481059/145868197-60a8034d-75ef-4285-872e-0e0714f01a4e.png)

And in album view they are displayed as follows:

![obraz](https://user-images.githubusercontent.com/22481059/145868968-1de7befa-263c-4e41-8ce8-cb89a34a3f0c.png)
![obraz](https://user-images.githubusercontent.com/22481059/145869095-ef5abd87-c6de-4ea3-a087-8e5db7cec881.png)

Another example for 'other versions' (here `$cfg['album_versions_indicator'][] = " (";` is important):

![obraz](https://user-images.githubusercontent.com/22481059/145869493-1b53694f-d6cc-4dfe-9edb-ebc1641ae4ff.png)
![obraz](https://user-images.githubusercontent.com/22481059/145869549-f57f81e1-b2d6-4d41-a4fc-fb0ae495cf6a.png)

**Comment by surtarso** [comment]
I renamed my multi discs as follows:
"The Album Title (2023)/The Album Title (2023) CD 01/The Artist Name - The Album Title CD 01 - 03 - Track Title"

I made a list with the most common formats found around (at least for me) that Lidarr will rename releases into. They are based on MusicBrainz information, so I got the list from there. Not sure all 3 types of spacing per format are needed, I just followed what was already there.

```
$cfg['multidisk_indicator'][] = "Disc ";
$cfg['multidisk_indicator'][] = " Disc ";
$cfg['multidisk_indicator'][] = " Disc";
$cfg['multidisk_indicator'][] = "Disk ";
$cfg['multidisk_indicator'][] = " Disk ";
$cfg['multidisk_indicator'][] = " Disk";
$cfg['multidisk_indicator'][] = "CD ";
$cfg['multidisk_indicator'][] = " CD ";
$cfg['multidisk_indicator'][] = " CD";
$cfg['multidisk_indicator'][] = "CD-R ";
$cfg['multidisk_indicator'][] = " CD-R ";
$cfg['multidisk_indicator'][] = " CD-R";
$cfg['multidisk_indicator'][] = "CD+G ";
$cfg['multidisk_indicator'][] = " CD+G ";
$cfg['multidisk_indicator'][] = " CD+G";
$cfg['multidisk_indicator'][] = "SHM-CD ";
$cfg['multidisk_indicator'][] = " SHM-CD ";
$cfg['multidisk_indicator'][] = " SHM-CD";
$cfg['multidisk_indicator'][] = "CD# ";
$cfg['multidisk_indicator'][] = " CD# ";
$cfg['multidisk_indicator'][] = " CD#";
$cfg['multidisk_indicator'][] = "Vol. ";
$cfg['multidisk_indicator'][] = " Vol. ";
$cfg['multidisk_indicator'][] = " Vol.";
$cfg['multidisk_indicator'][] = "Part ";
$cfg['multidisk_indicator'][] = " Part ";
$cfg['multidisk_indicator'][] = " Part";
$cfg['multidisk_indicator'][] = "Hybrid SACD ";
$cfg['multidisk_indicator'][] = " Hybrid SACD ";
$cfg['multidisk_indicator'][] = " Hybrid SACD";
$cfg['multidisk_indicator'][] = "SACD ";
$cfg['multidisk_indicator'][] = " SACD ";
$cfg['multidisk_indicator'][] = " SACD";
$cfg['multidisk_indicator'][] = "SHM-SACD ";
$cfg['multidisk_indicator'][] = " SHM-SACD ";
$cfg['multidisk_indicator'][] = " SHM-SACD";
$cfg['multidisk_indicator'][] = "HDCD ";
$cfg['multidisk_indicator'][] = " HDCD ";
$cfg['multidisk_indicator'][] = " HDCD";
$cfg['multidisk_indicator'][] = "HQCD ";
$cfg['multidisk_indicator'][] = " HQCD ";
$cfg['multidisk_indicator'][] = " HQCD";
$cfg['multidisk_indicator'][] = "Digital Media ";
$cfg['multidisk_indicator'][] = " Digital Media ";
$cfg['multidisk_indicator'][] = " Digital Media";
$cfg['multidisk_indicator'][] = "Vinyl ";
$cfg['multidisk_indicator'][] = " Vinyl ";
$cfg['multidisk_indicator'][] = " Vinyl";
$cfg['multidisk_indicator'][] = "Flexi-disc ";
$cfg['multidisk_indicator'][] = " Flexi-disc";
```
(in include/config.inc.php under 'unset($cfg['multidisk_indicator']);')

This fixed the image 'problem' that was happening where the update couldn't find the multi disc covers, on theory. Since they were actually there, but only on the root of the multi disc folders and not on their sub folders repeated. They would show normally, but the updater puts them as 'no image for X folders.' erroneously maybe? Since they show up normally...

But yeah, still I can't condense my albums into one, or know which CD they are... I have collections with 20+ cd's (like NOFX single albums collection etc) and its really hard on the eyes to see so many 'equal' cd's and have no idea which one is which... even when I click any I can't seem to know which disk it is (also a pain when you want to listen to the entire collection and have to click 20 cds to queue) but anyway, I will be trying a bit more here... but did I do something wrong?
It seems I followed your instructions correctly.

**Comment by ArturSierzant** [comment]
OK, let's focus on "45 or 46 Songs..." first. In album view I see that both albums have the same title "45 or 46 Songs That Weren't Good Enough" - it seems that that both albums have the same value of ALBUM tag written in mp3 files. You can check it in album view -> track menu -> file details:

![obraz](https://github.com/ArturSierzant/OMPD/assets/22481059/af9998c0-cbb2-46fc-8222-65ecfe938f6e)

![obraz](https://github.com/ArturSierzant/OMPD/assets/22481059/b944846d-1379-4331-b399-c1f58c755112)

![obraz](https://github.com/ArturSierzant/OMPD/assets/22481059/d2ebd7cd-3ee8-426f-b67d-969d5d484cb6)

Please check it for first track from each folder ("... CD 01", "...CD 02") and if they are really the same change them by adding e.g. " CD 01" to ALBUM tag in first folder and " CD 02" in second one. Then update each album and see if that made any difference.

**Comment by surtarso** [comment]
hmm... I dont really control the tags for my files since it tags from musicbrainz... 
I renamed (yet again) but removing the root folder of multiple albums, from:

"The Album Title (2023)/The Album Title (2023) CD 01/.....Track Title"
to:
"The Album Title (2023) CD 01/.....Track Title"

removing redundant art this way... and coz jellyfin now also splitted my albums, tho it knows cd numbers (I assume from tag)

It is re-scanning the library on ompd here, but as you can see from Lidarr (the one that fetches musicbrainz tags and puts them to file), the ALBUM has no disc number, but there are disc number indicators:

![image](https://github.com/ArturSierzant/OMPD/assets/54255356/19e15f17-2000-4b1d-9aab-b8257e4e56f9)

Ill edit this post once the scan is done (takes a while, 40k songs)

**Comment by ArturSierzant** [comment]
Yes, you need to update ALBUM tags - sorry I didn't explain that more clearly earlier.

Using the disc number/disc count/part of set tags wouldn't solve problem - for example: having albums in different formats (like CD and HD) or remastered and original albums we would need another tag to distinguish them.

**Comment by surtarso** [comment]
I see... so would it be doable to add said tags on the album info after we click them? 
this screen:
![image](https://github.com/ArturSierzant/OMPD/assets/54255356/bd297346-7c69-4e69-8113-3c65ddbc0ba3)

like popularity, genre, year...... part of set 1/18 (if any) or 'disc 1 of disc_count 18'? That would already help a lot, coz as it is the only way to know the album is to open the file info of an album file as we did on last post... 

If you point me to the file that handles this I could try to edit the php myself =)

**Comment by ArturSierzant** [comment]
In commit [11f5263](https://github.com/ArturSierzant/OMPD/commit/11f52635c596a6615c3080ba89488e4c2cbfb176) I added 'Disc no.' to album view. You need to enable it in _Settings -> Show disc number in album view_. 

Unfortunately, info about total number of discs in a set is not written to DB during update, so only disc number can be shown.

**Comment by surtarso** [comment]
Hey, thanks! That worked like a charm.
I really like this software you built. It's the music motor of my home =)

It would be a nice QoL to be able to click the artist name from the library view and go straight to artist page.
But I will leave you alone now! =))

Thanks again! I will close this issue.

**Comment by ArturSierzant** [comment]
You're welcome :)

**Comment by ArturSierzant** [comment]
One more change: in commit [40e8f60](https://github.com/ArturSierzant/OMPD/commit/40e8f60b9b9b2896a4e260e4713eb63d92e46104) I added disc number to albums in 'Other versions of this album' and 'Other discs in this set' in album view:

![obraz](https://github.com/ArturSierzant/OMPD/assets/22481059/58c7e13a-768c-48c4-8452-2443492c6205)

 Hope it helps you.

**Comment by surtarso** [comment]
You're the man.
![image](https://github.com/ArturSierzant/OMPD/assets/54255356/2e33e3f6-1f2f-4fe2-8294-c6e535be0ce1)

**Comment by surtarso** [comment]
hmm... Hey Artur, would you have any idea why some of the albums don't show as other versions?
these 2 albums for example:
![image](https://github.com/ArturSierzant/OMPD/assets/54255356/032e884f-08ee-4c20-b226-94222c354ff7)

the anthology does not how the both albums:
![image](https://github.com/ArturSierzant/OMPD/assets/54255356/9d385b2a-e2f7-45a0-8bd8-e5108d5a59ee)
and its metadata:
![image](https://github.com/ArturSierzant/OMPD/assets/54255356/9ca5830d-d349-4f51-b595-e2ab70ec0ba6)


now this other album does show:
![image](https://github.com/ArturSierzant/OMPD/assets/54255356/e8304e19-31b4-42fe-8575-a3aeed43b00e)
and its metadata seems to be the same as the other one:
![image](https://github.com/ArturSierzant/OMPD/assets/54255356/47ff32af-ee99-4d72-bd0d-854aad5d88a7)

I went on musicbrainz too, to see if I could find any difference I could correct on the metadata, but they seem identical.
Any light on that? I can't seem to find out why some show and some don't.

**Comment by ArturSierzant** [comment]
The key to grouping is right ALBUM tag - O!MPD reads data from metadata, it doesn't care about folder name.

In my case:
_The Lamb Lies Down On Broadway (2007 Remaster, 24bit-88.2kHz,_ **Disc** 1)
_The Lamb Lies Down On Broadway (2007 Remaster, 24bit-88.2kHz,_ **Disc** 2)
are grouped as one album because they have '**Disc** ' as part of the title (in ALBUM tag) and  '**Disc** ' is on `$cfg['multidisk_indicator']` list:

`$cfg['multidisk_indicator'][] = "Disc ";`

So O!MPD checks if any of items from `$cfg['multidisk_indicator']` list is a part of the title string and if yes then it treats left part of the title (starting from a place where this item is in the title) as core. Then it searches other albums that starts from core string and displays them as other discs. In the case above the core is '_The Lamb Lies Down On Broadway (2007 Remaster, 24bit-88.2kHz,_ '

On the other hand:

_The Lamb Lies Down On Broadway_**,** Disc 1
_The Lamb Lies Down On Broadway_**,** Disc 2

are listed as other versions of _The Lamb Lies Down On Broadway (2007 Remaster, 24bit-88.2kHz, Disc 1)_, because it has ' (' as part of the title and ' (' is on `$cfg['album_versions_indicator']` list:

`$cfg['album_versions_indicator'][] = " (";`

Here the rule is the same and core is _The Lamb Lies Down On Broadway_ - that's why 
_The Lamb Lies Down On Broadway_, Disc 1
_The Lamb Lies Down On Broadway_, Disc 2
are displayed as other versions of this album - they both starts from _The Lamb Lies Down On Broadway_

The albums are also grouped in artist view:

![obraz](https://github.com/ArturSierzant/OMPD/assets/22481059/1b7dc145-7920-41d9-a866-2bc76501e4bd)

In your case O!MPD sees all of _126 inches of NOFX: Singles Collection_ as other versions, because they all have the same title. To distinguish them you would have to add something like ' Disc 1', ' Disc 2', etc. to title in ALBUM tag, e.g.:
_126 inches of NOFX: Singles Collection, Disc 1_
_126 inches of NOFX: Singles Collection, Disc 2_
and add 'Disc ' to `$cfg['multidisk_indicator']` list:

`$cfg['multidisk_indicator'][] = "Disc ";`

Then '_126 inches of NOFX: Singles Collection,_ ' would be the core and all albums starting with this would be displayed as other albums in this set.
