### ISSUE TITLE
Youtube not working for me

### ISSUE THREAD

**Issue by brendan-pike** [ArturSierzant/OMPD#156]
I've not used the youtube feature before but would like to, I've installed youtube-dl.

From OMPD I get this error when trying
`{"insertPlayResult":"insert_error","album_id":null,"track_id":"youtube_Z_4ULKpkLNc","position_id":"50001"}`

If I try from command line I get this: 
```
www-data@Hyssop:~/OMPD$ youtube-dl -j --no-check-certificate --prefer-insecure Z_4ULKpkLNc 
ERROR: Z_4ULKpkLNc: YouTube said: Unable to extract video data
```
Any ideas please?

**Comment by ArturSierzant** [comment]
Try to update youtube-dl:
`youtube-dl -U`

I use version 2021.12.17 and 
`youtube-dl -j --no-check-certificate --prefer-insecure Z_4ULKpkLNc `
works for me.

I update youtube-dl everyday using crone.

**Comment by brendan-pike** [comment]
Yay it works thanks!
Discovered you can't youtube-dl -U on debian/ubuntu, so I purged that and manually installed the latest and also had to provide full path to youtube-dl.
