### ISSUE TITLE
[BUG] special character handling of filebrowser

### ISSUE THREAD

**Issue by othmar52** [ArturSierzant/OMPD#16]
Hi Artur,
Obviously the character handling of O!MPD's filebrowser needs some improvement. A directory named `aa'bb"cc<>+öµ⁄ä:²³¼¬{!()"§$%&⁄()=[]üalright plus + toll !"§$&⁄(⁄)=;::²³¼¬{[]}µ~||<<>>öäü+*ß&` produces crap in frontend. It's not that important for me but i just wanted to let you know...

[![ompd filebrowser handling special chars error](http://gas-werk.org/ompd/ompd-filebrowser-specialchars.png)](http://gas-werk.org/ompd/ompd-filebrowser-specialchars.png)

Of course i dont really have/use such named directories but testing my development of [sliMpd](https://github.com/othmar52/slimpd) makes me do strange things :)

**Comment by ArturSierzant** [comment]
Thanks, I'll try to fix it.

**Comment by othmar52** [comment]
hmmm
your commit 0267632030afcd246062072b775797e85573206b does not seem to have fixed this issue :)

**Comment by ArturSierzant** [comment]
Hm..., it works in my system - except I can't play file with this name (I don't know how to play file with `"` in name). But it displays OK. How do you see this issue?

**Comment by othmar52** [comment]
looking at the closing commit 0267632030afcd246062072b775797e85573206b made me feel that there hasn't been any changes. obviously you fixed this before.

Currently i havn't a vanilla O!MPD installation but just my fork. i soon as i am able to merge your master branch back into my fork i can try if your bugfix worked for me.
Any plans to dig through/merge these 8 open pull requests?
