### ISSUE TITLE
Music Player Daemon error play.php

### ISSUE THREAD

**Issue by marcbth** [ArturSierzant/OMPD#167]
Hello Artur,

one more thing:
at Now Playing
when I click on a song further ">" or "<",
I get 
Music Player Daemon error
Connection unexpectedly closed

Selecting a song from the list below works 
Cliff

**Comment by marcbth** [comment]
I used an old play.php and everything works.

can you help me, please.

**Comment by marcbth** [comment]
with the old play.php works back and forth but not the new functions of tidal (mix etc)

**Comment by marcbth** [comment]
this is the problem

function prev_() {
        global $cfg, $db;
        authenticate('access_play');
        require_once('include/play.inc.php');
        
        $data = array();
        /* $status = mpd('status');
        if ($status['song'] == 'stop') {
                mpd('play');
        } 
        mpd('previous'); */ 
  if ($status['song'] > 0) {
    mpd('stop');
    mpd('play ' . $status['song'] - 1); 
  }

**Comment by marcbth** [comment]
the old one in play.php works perfect

//  +------------------------------------------------------------------------+
//  | Prev                                                                   |
//  +------------------------------------------------------------------------+
function prev_() {
	global $cfg, $db;
	authenticate('access_play');
	require_once('include/play.inc.php');
	
	$data = array();
	$status = mpd('status');
	if ($status['state'] == 'stop') {
		mpd('play');
	}
	mpd('previous');
	if (get('menu') == 'playlist') {
		$status = mpd('status');
		if ($status['state'] == 'stop')		$data['state'] = '0'; // stop
		if ($status['state'] == 'play')		$data['state'] = '1'; // play
		if ($status['state'] == 'pause')	$data['state'] = '3'; // pause
		$data['idx'] = $status['song'];
		echo safe_json_encode($data);
	}
}

**Comment by ArturSierzant** [comment]
That's strange - this change was made 1.5 year ago. I don't remember exactly why, but I think it had something to do with situation when you have only one track on playlist. Anyway, since then I hadn't have any problems with `prev` or `next` functions. 

I wonder where the real problem is?  Maybe try to replace in `prev_()`:
`mpd('play ' . $status['song'] - 1);`
with:
`mpd('previous');`

and in `next_()`:
`mpd('play ' . $status['song'] + 1);`
with:
`mpd('next');`


What is your mpd version? I use 0.23.12 and 0.23.4.

**Comment by marcbth** [comment]
when I do this I get



Music Player Daemon Error

Error: ACK [55@0] {next} Will not play

Command: next

and the progress bar time always runs through and does not show the corresponding time played 


i used a new install debian amd64 12.04 with mpd from deb multimedia version xxx0.13

**Comment by marcbth** [comment]
Hello Artur, 

after your last update yesterday (20.01.23) it is working again.



Thanks for your great work



Cliff

**Comment by marcbth** [comment]
works for me

function next_() {
        global $cfg, $db;
        authenticate('access_play');
        require_once('include/play.inc.php');
        
        $data = array();
        $status = mpd('status');
        if ($status['state'] == 'stop') {
                mpd('play');
        }
        mpd('next');
        if (get('menu') == 'playlist') {
                $status = mpd('status');
                if ($status['state'] == 'stop')         $data['state'] = '0'; // stop
                if ($status['state'] == 'play')         $data['state'] = '1'; // play
                if ($status['state'] == 'pause')        $data['state'] = '3'; // pause
                $data['idx'] = $status['song'];
                echo safe_json_encode($data);
        }
}

**Comment by ArturSierzant** [comment]
The problem was in unnecessary commands `mpd('stop')` - when MPD is in `stop` state it is not possible to execute commands `next` and `previous` - an error is issued. I modified a little bit these functions and now they should work right. 

Thanks for reporting this problem.
