### ISSUE TITLE
Update getID3.

### ISSUE THREAD

**Issue by dseomn** [ArturSierzant/OMPD#21]
Hi,

Would you mind updating the bundled copy of getID3 to the latest version? https://github.com/JamesHeinrich/getID3/commit/f4e51aabbd78eb52f08c0e0257b2d0f0b7c1463a should fix an issue I have with some of my files in O!MPD.

**Comment by othmar52** [comment]
@Artur: Maybe this would be a good point to switch to [https://getcomposer.org/](composer). Are you familiar with it? It's something like a package manager for all your extrnal libraries (jquery, getid3, fonts, github-projects,...). In case you are interested i can copy/paste the relevant setup from sliMpd and create a pull request

**Comment by ArturSierzant** [comment]
Done in commit 0c6b8d9.
