### ISSUE TITLE
Multi-disc album tagged as one album plays in wrong order.

### ISSUE THREAD

**Issue by dseomn** [ArturSierzant/OMPD#22]
My multi-disc albums are all tagged as single albums with discnumber tags. O!MPD loads them in the wrong order, sorted by tracknumber instead of by (discnumber, tracknumber). Here are some example files (ignore the filenames, they're not in order): [multi-disc-single-album.zip](https://github.com/ArturSierzant/OMPD/files/638437/multi-disc-single-album.zip)

**Comment by dseomn** [comment]
And here are the same files but in MP3 format: [multi-disc-single-album-mp3.zip](https://github.com/ArturSierzant/OMPD/files/638450/multi-disc-single-album-mp3.zip)

**Comment by ArturSierzant** [comment]
Fixed in f5ebd96, now it should work correctly.
