### ISSUE TITLE
Long track titles are truncated.

### ISSUE THREAD

**Issue by dseomn** [ArturSierzant/OMPD#23]
I have a track with a title of "The Preachers of Crimetheus: Ballet in One Selfless Act, S. 988: III. Finale: Special Deliverance: Theme (windbreaker) / Variation 1 (balloons) / Variation 2 (slide whistle) / Variation 3 (slide windbreaker) / Variation 4 (lasso d’amore) / Variation 5 (foghorn, bells, kazoo)", but O!MPD shows it as "The Preachers of Crimetheus: Ballet in One Selfless Act, S. 988: III. Finale: Special Deliverance: Theme (windbreaker) / Variation 1 (balloons) / Variation 2 (slide whistle) / Variation 3 (slide windbreaker) / Variation 4 (lasso d’amore) / Variation 5 (fo". Would you mind increasing the field length of track titles (and possibly also album names and artist names, I haven't checked) to something less likely to cause truncation? Maybe 4096?

**Comment by ArturSierzant** [comment]
Done in c658cf5 - I decided to increase this fields to 333, because this is the index limit for MyISAM with UTF-8. I tried largest fields (4094 as you suggested) with index limited to 333, but it degraded performance of DB significantly. I hope 333 is enough...
