### ISSUE TITLE
Add genre column to tracklists.

### ISSUE THREAD

**Issue by dseomn** [ArturSierzant/OMPD#31]
The Now Playing page has a genre column in the tracklist, but album and artist pages do not. How would you feel about having a genre column in those tracklists (and possibly other ones I haven't noticed are missing the column)? I can probably write the patch if you think it's a good idea.

**Comment by ArturSierzant** [comment]
Done in 2479300. In album view `genre` will appear only when not all tracks have the same genre (I think it doesn't make sense to display genre when all tracks have the same one). In other views `genre` now appears always.

**Comment by dseomn** [comment]
Thank you!
