### ISSUE TITLE
CLI database update fails.

### ISSUE THREAD

**Issue by dseomn** [ArturSierzant/OMPD#32]
Here's what I get when I try to update the database from the command line:

```
root@bajor:/var/www/html/ompd# sudo -u www-data php update.php 
PHP Fatal error:  Call to undefined function cliUpdate() in /var/www/html/ompd/update.php on line 57
```

**Comment by ArturSierzant** [comment]
CLI update is a part that left of Netjukebox - it doesn't work in O!MPD for now. I'll consider to remove this part of code.
