### ISSUE TITLE
Can't update Database

### ISSUE THREAD

**Issue by virse** [ArturSierzant/OMPD#33]
Hi Artur,

I recently had to switch my OMPD installation to another computer due to problems with the os (ubuntu 14.04).

So I copied the old installation, the config file and so on to the new server. Due to the failure of the old system I wasn't able to make a dump of my mysql-db. I can access OMPD and I can also start the update process to build the db again from scratch.

But the db isn't filled. When I debug the update, I can get only this in the log-file:

```
Update started /var/www/ompd2/tmp/update_log.txt
Update start time: 20170104 10:38:05
recursiveScan: /mnt/samba/
Update stop time: 20170104 10:46:51
```

The samba share is accessible by the user that runs the apache2-webserver. The same user is also the mpd-user. I get no permission errors or anything else.

I use apache2 with mariadb and PHP7 on Debian Stretch (because I use an ARM64 device and MPD isn't available in the repo of Jessie) - all the necessary requirements are installed as you can see (from php.info within OMPD):

```
_fileinfo_
fileinfo support 	enabled
version 	1.0.5
libmagic 	522 

_gd_
GD Support 	enabled
GD headers Version 	2.2.3
GD library Version 	2.2.3
FreeType Support 	enabled
FreeType Linkage 	with freetype
FreeType Version 	2.6.3
GIF Read Support 	enabled
GIF Create Support 	enabled
JPEG Support 	enabled
libJPEG Version 	6b
PNG Support 	enabled
libPNG Version 	1.6.26
WBMP Support 	enabled
XPM Support 	enabled
libXpm Version 	30411
XBM Support 	enabled
WebP Support 	enabled 

_iconv_
iconv support 	enabled
iconv implementation 	glibc
iconv library version 	2.24 

_mysqli_
MysqlI Support	enabled
Client API library version 	mysqlnd 5.0.12-dev - 20150407 - $Id: 241ae00989d1995ffcbbf63d579943635faf9972 $
Active Persistent Links 	0
Inactive Persistent Links 	0
Active Links 	1 
```

It seems that the update do the Structure & image process, but not the file info process (and the rest) anymore.

Any clues?

Thx again for your support! I appreciate that a lot!

Michael

**Comment by virse** [comment]
Hi Artur,

after a little bit of searching I was able to find out why the scan wasn't working. My instance of the MariaDB hat some issues. When I changed back to MySQL everything works like a charme.

Maybe it helps others too, when using MariaDB as default SQL-Sever,

Greets Michael

**Comment by ArturSierzant** [comment]
Do you know what was the problem with MariaDB?

**Comment by virse** [comment]
Hi Artur,

I'm not sure but I use Debian Stretch as my underlying OS due to the fact that there is no 64bit-arch for mpd yet in the jessie-repofor odroid-c2 (arm).

Maybe the sometimes unstable software of the stretch-branch was the problem.

Greets

**Comment by ArturSierzant** [comment]
I tested O!MPD with MariaDB and there were no problems, so maybe it was really problem with this particular instance of MariaDB. I'm closing this issue.
