### ISSUE TITLE
Suggestion:  Building playlist with same kind of music

### ISSUE THREAD

**Issue by virse** [ArturSierzant/OMPD#34]
Hi Artur!

I have one suggestion for your great project. I don't know if you have used Last.fm in the past (really in the past ;o) )? There was a option to listen to other songs/artists which represent/play the same kind of music. 
For example when you are listening to a song from lets say ACDC Last.fm suggested bands/artists as GunsnRoses or othre Hard Rock acts and added this suggestions to the playlist.

Maybe there is a possibility to implement such a feature to O!MPD? 

Greets Michael

**Comment by brendan-pike** [comment]
Isn't this pretty much what genres are for?
