### ISSUE TITLE
Albums with more than 99 tracks split into multiple discs.

### ISSUE THREAD

**Issue by dseomn** [ArturSierzant/OMPD#36]
While looking at 0f13f27, I saw what looks like a bug, but I haven't tested it. I think any disc with more than 99 tracks will be parsed as multiple discs by parseDiscNumber.

**Comment by ArturSierzant** [comment]
Now data from tags `part_of_a_set` or `discnumber` have priority over `tracknumber`, so all tracks tagged `discnumber = 1` will belong to that disc no matter what track number they have. Thanks for pointing that.

**Comment by dseomn** [comment]
Thanks!
