### ISSUE TITLE
Error adding track with " in title.

### ISSUE THREAD

**Issue by dseomn** [ArturSierzant/OMPD#37]
I just got the below error when I tried to add an album to the queue. I think it's because the track title has double quotes (") in it.

```
Error: ACK [2@0] {addid} Space expected after closing '"'
Command: addid "Hoag, Andrea, Kelley, Loretta & Pilzer, Charlie with Brown, Frank & Robinson, Larry/Hambo in the Barn/d01t11. Andrea Hoag, Loretta Kelley & Charlie Pilzer with Frank Brown & Larry Robinson - "Burträsk hambo" (Hambo-polska efter Lars Persson) _ Hambo in the Barn.flac.ogg" 
```

**Comment by ArturSierzant** [comment]
Yes, I've noticed this too. The problem is that I don't know how to add to MPD tracks with `"` - MPD treats this as end of string... Maybe you have any idea?

**Comment by dseomn** [comment]
I dug around the libmpdclient source code and found http://git.musicpd.org/cgit/master/libmpdclient.git/tree/src/quote.c, which appears to be how libmpdclient sends the URI argument to the addid command. Basically, replace `"` with `\"` and `\` with `\\`.

**Comment by ArturSierzant** [comment]
Done in bc80215 - thanks for hint.
