### ISSUE TITLE
Not all genres show up on an album.

### ISSUE THREAD

**Issue by dseomn** [ArturSierzant/OMPD#38]
I have an album with more than 3 genres, but only 3 genres show up on the album page. I think it's because the `album.genre_id` field is a `varchar(10)`. Could you increase it to at least 255 please?

**Comment by ArturSierzant** [comment]
I'll correct this together with #23 - this should be done using incremental DB update from Netjukebox, which modifies not only new instances of DB, but also existing ones.

**Comment by ArturSierzant** [comment]
Done in c658cf5.
