### ISSUE TITLE
Undefined index : Name

### ISSUE THREAD

**Issue by eoli3n** [ArturSierzant/OMPD#4]
Hi,
I see in nginx logs that i have 1 errors / sec since longtime

```
2016/10/17 21:12:30 [error] 564#564: *5372 FastCGI sent in stderr: "PHP message: PHP Notice:  Undefined index: Name in /srv/http/ompd/play.php on line 1188" while reading response header from upstream, client: 127.0.0.1, server: localhost, request: "GET /ompd/play.php?action=playlistStatus&menu=playlist&ajax=1 HTTP/1.1", upstream: "fastcgi://unix:/run/php-fpm/php-fpm.sock:", host: "127.0.0.1", referrer: "http://127.0.0.1/ompd/playlist.php"
```

**Comment by ArturSierzant** [comment]
I've just fixed it - check it out please (master branch).

**Comment by eoli3n** [comment]
Still lots of errors
http://sprunge.us/XXaS

Maybe it is because i run multiple ompd, with same socket ?
nginx run your OMPD, ompd_test and ompd_test2

**Comment by ArturSierzant** [comment]
I think it's just code issue. Try this: http://ompd.pl/downloads/less/index.zip

**Comment by eoli3n** [comment]
better, but still a last one : http://sprunge.us/eMIB

**Comment by ArturSierzant** [comment]
I've fixed some more. To prevent displaying notice messages, I've changed `error_reporting` in _initialize.inc.php_ from `0` (i.e. report all errors) back to its default value (`E_ALL ^ E_NOTICE`).

**Comment by eoli3n** [comment]
http://sprunge.us/FOcS
still errors, but just once, when connecting to mariadb i think. No errors comming after this

**Comment by ArturSierzant** [comment]
Yes, this should appear only when the connection to db is not properly defined. In case of proper config, log should be clean. 
I think this would close this issue.
