### ISSUE TITLE
update.php Warning

### ISSUE THREAD

**Issue by TW61** [ArturSierzant/OMPD#41]
filemtime(): stat failed for "files with special Characters" in /var/www/html/ompd/update.php on line 674

please see http://stackoverflow.com/questions/7639292/filemtime-function-filemtime-stat-failed-for-filenames-with-umlauts

**Comment by ArturSierzant** [comment]
Hi, thanks for reporting that. Please check, if `$cfg['default_filesystem_charset']` in your `config.inc.php` (or `config.local.inc.php`) is correctly set.

**Comment by TW61** [comment]
I changed "config.local.inc.php" and now the warning is gone. Thank you.
