### ISSUE TITLE
recursive ajax call on invalid/missing configuration

### ISSUE THREAD

**Issue by othmar52** [ArturSierzant/OMPD#5]
I have cloned the O!MPD repo and did **NOT** configure anything.
When i access it in my browser O!MPD turns crazy with an endless request loop

```
Failed to create database:
ompd
```

**Comment by ArturSierzant** [comment]
I almost forgot about this... Now should be OK.
Thanks for feedback.

**Comment by othmar52** [comment]
Thanks for fixing this issue that fast!
one hint: a tiny change in your commit message could resolve/close/reference this issue [by commit message](https://help.github.com/articles/closing-issues-via-commit-messages/)

instead of `Fix issue#4` use `Fix #4` as commit message ;)

**Comment by ArturSierzant** [comment]
Thanks for hint - I've just used it :)
