### ISSUE TITLE
Add support for stop button

### ISSUE THREAD

**Issue by mogwa1** [ArturSierzant/OMPD#50]
I really like OMPD and am using it to control my multi-room music playback system at home.  

One of the things that I'm missing is a "stop" button.  I realize that for most (local) playback, the pause button is sufficient.  However, I play quite a lot of internet music streams.  In those cases, if you "stop" the stream using the "pause" button and resume the stream later, it will run into issues with the current buffer content versus the actual stream content at the time the playback is resumed.  It's actually quite annoying after a while.

I noticed that all the code for the stop button is still in the source code, so I've re-enabled it on my side, and everything seems to work fine (tested this for several months with 1.02).  I can provide a patch if you like.
Although I can imagine that you want to make this configurable...

**Comment by ArturSierzant** [comment]
Done in 617c6e5 - long press on 'play/pause' button sends stop command to MPD.
