### ISSUE TITLE
Add support for mpd "consume" mode

### ISSUE THREAD

**Issue by mogwa1** [ArturSierzant/OMPD#51]
OMPD has a "delete played" option.  However, it seems to just delete the songs which come before the currently played track in the playlist.  This has some inherent drawbacks: if you use shuffle mode, it will just remove random songs from the playlist, not necessarily the ones that have already been played.

Since OMPD only supports mpd as backend player, wouldn't it make sense to use the mpd built-in "consume" mode?  In that mode, mpd will simply remove the current track from the playlist once it has finished playing.  This approach works fine in shuffle mode.  The only difference is that you have to switch this on before you start listening (it will have no effect on the tracks that have already been played up to the time you switch it on).

**Comment by ArturSierzant** [comment]
Done in 617c6e5 - long press in 'delete played' toggles consume mode. When consume mode is on, 'delete played' is displayed as 'delete played [auto]'.
