### ISSUE TITLE
Sqlite as database

### ISSUE THREAD

**Issue by mistepien** [ArturSierzant/OMPD#56]
It would be great in case of really embedded systems (eg. routers  with openwrt and 16MB of flash) to enjoy OMPD with sqlite instead of so mainframe-like software like mysql.

**Comment by ArturSierzant** [comment]
In this stage it would be very difficult to change DB to sqlite - a lot, lot of work. And I don't know what would be the performance of sqlite for large collections (1000s of albums). If I ever dared to change it, I probably would choose something more universal like PDO. But it's rather far future...
