### ISSUE TITLE
mpd crashes when adding album

### ISSUE THREAD

**Issue by xkonni** [ArturSierzant/OMPD#58]
For some reason this happens on my system. Playing perfectly fine, adding albums via ompd sometimes results in a mpd crash. Only output I get from mpd is this:

```
Feb 01 12:49:22 innocence systemd[1]: mpd.service: Main process exited, code=killed, status=11/SEGV
Feb 01 12:49:22 innocence systemd[1]: mpd.service: Failed with result 'signal'.
```

System: 
Archlinux, running 4.14.15-1-ARCH
Music Player Daemon 0.20.15
currently listening via httpd plugin

It does not happen when using other clients, like ncmpcpp so i assume it's something about ompd. 
is there some way to show logs? the debug parameter only seems to affect logging database updates.

**Comment by ArturSierzant** [comment]
Hi,
you're right, `debug` works only for database update. But you can try with mpd option `log_level` set to `verbose` - maybe mpd will log something that helps to find the problem.

**Comment by xkonni** [comment]
Hey,

that's where those 2 lines came from, unfortunately it's not really verbose in this matter.

Thanks for your help!

**Comment by ArturSierzant** [comment]
I have no idea, what could be the reason. Does it happen for different albums? Maybe for albums with any special characters in album/track title?
I'll try to compile version 0.20.15 and check if problem appears in my system (RasPi3 with Raspbian).

**Comment by xkonni** [comment]
Hey Artur,

this might also be related to the mpd-httpd output. It does not happen
without that one active, yet with e.g. ncmpcpp it does not crash either.
I'll keep an eye open for any useable debugging output, but for now I don't
think its purely ompd related, maybe the combination of both: ompd &
mpd-httpd.

**Comment by ArturSierzant** [comment]
One more thing: does O!MPD play files or streams? When O!MPD plays streams you can see it in Now Playing: there should be text `(stream)` next to file type, under the time bar. In this case mpd receives stream prepared by O!MPD - maybe this causes the problem?

**Comment by xkonni** [comment]
It plays files from the local disk to multiple outputs (toslink to the amp,
httpd or snapcast for multiroom clients, null to make sure it keeps
playing). It's probably related to httpd, but as mpd hardly outputs any
verbose logs, hard to tell.

**Comment by xkonni** [comment]
okay, just double-checked

### without httpd
* ``` mpc clear; mpc add artist/album; mpc play ```
  * works
* ompd -> add & play multiple albums
  * works

### with httpd
* ``` mpc clear; mpc add artist/album; mpc play ```
  * still works
* ompd -> add & play multiple albums
    * crashes mpd

### httpd output config 
```
audio_output {
    type            "httpd"
    name           "httpd"
    port             "6800"
    encoder       "flac"          # flac
    compression "0"           # flac
    format        "44100:16:1"
    always_on   "yes"
    tags             "yes"
}
```

So it's some combination of httpd-output and ompd. Maybe the frequency of sending commands? Can't think of anything else.

**Comment by ArturSierzant** [comment]
I've found the bug and corrected it in 6aa0a45 - it helped in my case, please check, if it also helps in yours.

**Comment by xkonni** [comment]
yes that seems to have fixed it.

awesome, thank you!

**Comment by ArturSierzant** [comment]
Good to hear that. Thank you for reporting this issue.
