### ISSUE TITLE
invalid installation instructions or missing directories

### ISSUE THREAD

**Issue by othmar52** [ArturSierzant/OMPD#6]
Hi Artur,
your [installation-instructions](http://ompd.pl/configuration#post-393) reads
```
Make sure that your web server has write access to directories:
/ompd/tmp/ (required for database update)
/ompd/stream/ (required for streaming files)
/ompd/cache/ (required for downloading files)
```
i did **NOT** download the zip file like stated in your installation-instructions but simply cloned the repo from github.
After cloning i cant see the directories `stream` and `cache` so i expect those dirs have to be created manually!?

consider to include all required directories in the git repo and add a file like [this](https://github.com/othmar52/slimpd/blob/master/localdata/cache/.gitignore) in those dirs

**Comment by ArturSierzant** [comment]
This dirs are created automatically during first time usage of stream or download features, but I added it to repo as you suggested. Thanks for hint.

**Comment by othmar52** [comment]
>This dirs are created automatically during first time usage of stream or download features

Hmmm. Does this mean O!MPD needs/needed write permissions for the DocumentRoot itself? that is not a good practice! ẃrite-permissions for web-applications should be limited as much as possible.

**Comment by ArturSierzant** [comment]
O!MPD only needs write permissions for `stream`, `cache` and `tmp` dirs. In normal case (thanks to you now also in github repo) those dirs are already created in zip/repo.
