### ISSUE TITLE
Now Playing isn't showing the info for the current track.

### ISSUE THREAD

**Issue by dseomn** [ArturSierzant/OMPD#62]
After upgrading from e166fad to 6aa0a45, the "Now Playing" page stopped showing information correctly:

![screenshot from 2018-02-10 12-50-53](https://user-images.githubusercontent.com/15314936/36064948-3c765d78-0e61-11e8-9bde-6b4744214e3b.png)

I don't see anything in the server logs. In the developer console, I see a bunch of requests to `play.php?action=playlistStatus&menu=playlist&ajax=1` with responses like the below.

```
{"hasStream":"false","hash":"ba1f8a4ade12322d19cdd8ded6890186","listpos":0,"volume":-1,"repeat":0,"shuffle":0,"consume":"0","name":"","title":"Menu (original)","track_artist":"小林啓樹","relative_file":"Various Artists\/Super Smash Bros. for Nintendo 3DS_Wii U_ A Smashing Soundtrack\/d01t01. 小林啓樹 - Menu (original).flac.ogg","Time":132000,"isStream":"false","audio_dataformat":"OGG","end_time":"15:22","end_in":"02:32:43","total_time":"02:34:54","audio_bits_per_sample":"16","audio_sample_rate":"44100","audio_profile":"0 kbps","isplaying":3,"miliseconds":130774,"gain":"album"}
```

**Comment by ArturSierzant** [comment]
Does it happen for any track or only for the particulars ones?

**Comment by dseomn** [comment]
I tried a handful of tracks, and it (or something similar) seemed to happen for all of them:

![screenshot from 2018-02-13 16-31-04](https://user-images.githubusercontent.com/15314936/36174912-c3e1c12c-10db-11e8-968c-1b0805ab863e.png)
![screenshot from 2018-02-13 16-31-58](https://user-images.githubusercontent.com/15314936/36174913-c3f2afbe-10db-11e8-8d0f-9225cd2b1635.png)
![screenshot from 2018-02-13 16-32-47](https://user-images.githubusercontent.com/15314936/36174914-c409e4b8-10db-11e8-9c55-7b9d41ccbae3.png)
![screenshot from 2018-02-13 16-33-25](https://user-images.githubusercontent.com/15314936/36174915-c423f60a-10db-11e8-8d89-f17ece81d8a1.png)

In the last screenshot, note how the track title is unchanged from the track before.

**Comment by dseomn** [comment]
Here are some errors in the console that might be relevant:

![screenshot from 2018-02-13 16-39-52](https://user-images.githubusercontent.com/15314936/36175359-21a9e478-10dd-11e8-849e-1fe59360d436.png)

**Comment by ArturSierzant** [comment]
Try to comment lines 851-853 in file `playlist.php`:

`//if (testing == 'on') {`
`//delimiter[1] = delimiter[1].replace(';','&');`
`//}`

**Comment by dseomn** [comment]
That did something, but definitely still not right:

![screenshot from 2018-02-15 12-58-24](https://user-images.githubusercontent.com/15314936/36272591-fd0a249c-124f-11e8-8b41-c83c5d5513a0.png)

The console still shows: `SyntaxError: JSON.parse: unexpected end of data at line 1 column 1 of the JSON data`

My local config includes `unset($cfg['artist_separator']);` because I don't want OMPD to guess at individual artists from the `artist` tag. (There's a separate `artists` tag with the correct list that I'd be happy to use, but I don't want guessing from `artist`.) In previous versions of OMPD that worked fine, but maybe that's why the artist info is showing up wrong now?

**Comment by ArturSierzant** [comment]
I think, I found a problem - I'll fix it in next commit. For now try to change
`$cfg['artist_separator'] = array();`
to 
`$cfg['artist_separator'][] = "qweqweqwewqeq";`
or to any string, that is not a part of any of your artist name.

**Comment by dseomn** [comment]
All better, thanks! Should I make the same change to `$cfg['separator']` or any other config var, or is `artist_separator` the only one affected by that problem?

**Comment by ArturSierzant** [comment]
No need to do other changes (as long as it works ok ;)). In c314efc I corrected the problem you'd reported, so now your setting `$cfg['artist_separator'] = array();` should also work. 
Thank you for notice this.
