### ISSUE TITLE
Multi disc albums

### ISSUE THREAD

**Issue by paulstephane** [ArturSierzant/OMPD#63]
Hi, first of all, congratulations on your excellent work.
I have a request concerning albums with multiple discs. Instead of grouping them based on the disc name, would it be possible to use the disc number tag? This way, the album title can be unique.

**Comment by ArturSierzant** [comment]
I'm not sure, if I get you right. When all the tracks of multidisc album are in one directory, then tags `part_of_a_set` or `discnumber` are used to group tracks into separate discs (when these tags are empty, then tracks' numbers are used: 101 -> disc#1, 201 -> disc#2, etc.). But I think, you are talking about different case...

**Comment by paulstephane** [comment]
Thanks I will test this again

**Comment by ArturSierzant** [comment]
There was small bug in update procedure which could generate this issue. It was fixed in d894c9c. Now this should work OK.
