### ISSUE TITLE
How can I reset the database?

### ISSUE THREAD

**Issue by paulstephane** [ArturSierzant/OMPD#64]
Is there a simple way to completely reset (erase)  the database? Thanks

**Comment by ArturSierzant** [comment]
Hi, there is no easy way you could do it from O!PMD. But two workaround solutions come to my mind:

1. in `config.inc.php` change `$cfg['media_dir']` to dir with no media files and update DB (config -> update all) - all data concerning albums/tracks/artists/genres/covers will be deleted (except some statistics data)

2. change the name of database: `$cfg['mysqli_db']`. Then new, empty DB will be created. Of course, old DB remains untouched. 

If you want to completely remove database, you have to use something like phpMyAdmin or mysql command line tool.

**Comment by paulstephane** [comment]
Thanks
