### ISSUE TITLE
[question] file errors - invalid mpeg audio header (on a MP3 file)

### ISSUE THREAD

**Issue by ffatgit** [ArturSierzant/OMPD#68]
Hello Artur, I have these faults after importing some test files (via a mounted usb-stick). It seems that anything is wrong in the files (all the similar cause). But what is the cause in detail and how can I debug this more in detail. In My ID3Tag tool (puddle in a Ubuntu 16.04 OS) all paramter/fields seems to be ok/plausible. Do you have an idea? (Because I'm afraid, that this will be the same issue on all my files (= thousands from files).

The thing is, that the files are playing without any problem and even the ID3Tag informations shown plausible. 

Screenshot:
![ompd_file_error](https://user-images.githubusercontent.com/21111020/41623250-7412a19e-7412-11e8-9f4d-6b3f113a52ee.png)

Zipped-Sample track in format MP3:
[Tremonti (2018) - A Dying Machine - 11.  As The Silence Becomes Me.zip](https://github.com/ArturSierzant/OMPD/files/2116871/Tremonti.2018.-.A.Dying.Machine.-.11.As.The.Silence.Becomes.Me.zip)

Thank you very much!
Frank

**Comment by ArturSierzant** [comment]
Hi Frank, 
thanks for reporting that. Those errors are generated by getID3, which I use to read tags from files. I think you could report it on its GitHub repo (https://github.com/JamesHeinrich/getID3). I've updated getID3 to the newest version (1.9.15-201805181907), but those errors still appear.
 
Meanwhile I wrote a temporary solution. You need to change file `/include/tagProcessor.inc.php`.  Replace function `parseError` with this one:

```
function parseError($data) {
    if (isset($data['error'])) {
				if (count($data['error']) == 1 && strpos($data['error'][0],'Invalid MPEG audio header') !== false) {
					return '';
				}
				
				return implode('<br>', $data['error']);
    }
    return '';
}
```

This will ignore `Invalid MPEG audio header` error, but only in case, when there are no other errors in mp3 file. Your files should import correctly, but O!MPD will still not read covers from those files, so you need to have cover in separate file (defined in `$cfg['image_front']`). If this is a problem for you, let me know - I'll try to modify import procedure to ignore this error also for updating covers from embedded pictures.

**Comment by ffatgit** [comment]
Hello Artur, 
WOW - very quick response/feedback!
I took your "workaround" into the file  /include/tagProcessor.inc.php. Then I try with "Gear wheel" butten; then "Update" (in the "Configuration") with the Button "Update All", but nothing happens:
Screenshot:
![Uploading Ompd_Update_No-Change.png…]()

Then I play a little bit around. Even via the "Update All" from the menue bar (that means this time not via the way over "Gear wheel" button.  But nothing changes.
By the way: These test files located on a USB stick. So I selected the folder with the music manua.
Screenshot:
![ompd_update_select-folder](https://user-images.githubusercontent.com/21111020/41681623-702f01a8-74d5-11e8-9cd2-55523a43093d.png)

l and use "Update this directory only". This end with success.
Screenshot:
![ompd_update_ok-change](https://user-images.githubusercontent.com/21111020/41681658-8b497b3a-74d5-11e8-9cf7-7ecd5efd196f.png)

Is it possible, that the button "Update All" don't covers all/sub folders (e.g. no external drives)?

To your question with the cover artwork: That is okay for me, because in every folder (to each album) the image what is integrated in the files is although there. I only have to (copy and) rename them. Because right know the image is named like the album plus  some informations. But the software needs a common image file name at this point. So I choose the default "folder.jpg" (as many other audio/player software uses (well-known example is apple itunes, so far I now). 

So thank you very much for the first round!
Frank

**Comment by ffatgit** [comment]
Hello Artur;
James of getid3 fixed the issue yesterday (it was a problem only at mp3 files with VBR).
I tried to update the getid3 in the ompd with copy the getid3.php into the getid3 folder. But from moment, an Update (pushing one of the possible button) results in a "white" webpage.

Have you any tip?
Thank you!
Frank

**Comment by ArturSierzant** [comment]
Try to replace whole _ompd/getid3_ dir with new one downloaded from getid3 repo.

**Comment by ffatgit** [comment]
Hello Artur,
sorry for the delayed response. I tried the last hours to try the ting running; BUT...
(I failed in the basics. Please refer to new "[Question] fresh install of ompd on dietpi distro V6.9")

**Comment by ffatgit** [comment]
Hello Artur,
with a successful basic / fresh installation I: 
- stopped all services (mpd, webserver, mariadb, ...)
- cross changed the directory "getid3" (with the sub content) source is the getid3-master from James Heinrich
- for this I kill/delete the `"getid3"` folder (and sub content) with command:
 `rm -r /var/www/ompd/getid3`
- then I copied the new folder from a mounted usb stick "bh" from source folder "data" (and sub content) with command:
`cp -r /mnt/bh/data/getid3/* /var/www/ompd`
- start all services
- open ompd
- logged in as admin
- start the update function
- result is a "white" page in the webbrowser
------------------------------
then the I reboot the device and try again.
same "white" page
url in this case is:
http://192.168.178.69/ompd/update.php?action=update&sign=W2ETH2jXji46h77ivXv8AHTcQUz2kTO_fYkta4MR
with a refresh of the browser
the message "Signature expired" is shown
------------------------------
then I activate the ompd log and retry.
the content/entries of the log file is "Update has started"
nothing more
------------------------------
Did I anything wrong? Any tip?
Thank you!

**Comment by ArturSierzant** [comment]
Looks like update procedure stops at very early stage - before (or maybe at?) including `getid3.php`. Please check error log for php. Also please make sure that dir structure is correct: path to file `getid3.php` should look like this: `ompd/getid3/getid3/getid3.php`. It's case-sensitive.

**Comment by ffatgit** [comment]
Hi,
thank you for feedback: And yes you were right, "the" middle getid3 folder was missing in my path.
Sorry, that I makes this rookie faults.
So whit the structure and the bug-fixed files from getid3-Master (download from github) I started the Update again. The Update sequence started and go through O!MPD as the first time. But sadly with no better result to my mp3 VBR files. The result was again "invalid header" faults.
I read the your entries in the getid3 repo (and the answers of James Heinrich) but I don't understand the details. So let me ask you:
Did you had really success with the fixes of getid3 on my test file?
Did you change anything else than the getid3 part?
Could I change or better add anything in my mp3 files. I mean a "VBR header" (because the bufix description in getid3 is 
>  bugfix #163 - invalid MP3 header error on VBR
#163
VBR files with no VBR header would generate a false "invalid mpeg audio
header" on every file
> 
But how this could be done and how a VBR header looks like?
Any idea?

**Comment by ArturSierzant** [comment]
One more thing: to get rid of this error you need also to change 2 things in `include/getID3init.inc.php':

1. `$getID3->option_tag_id3v1 = true;` (old value is `false')
2. `$getID3->option_tag_lyrics3 = true;` (old value is `false')

After this, I hope, update should work OK.

**Comment by ArturSierzant** [comment]
One more thing: to get rid of this error you need also to change 2 things in `include/getID3init.inc.php':

1. `$getID3->option_tag_id3v1 = true;` (old value is `false')
2. `$getID3->option_tag_lyrics3 = true;` (old value is `false')

After this, I hope, update should work OK.

**Comment by ffatgit** [comment]
Hi Artur,
tried your last tips and the result was an update without faults!
Thank you very much.
Will use and explore O!MPD further!
