### ISSUE TITLE
[Question] fresh install of ompd on dietpi distro V6.9 fail

### ISSUE THREAD

**Issue by ffatgit** [ArturSierzant/OMPD#70]
Hello Artur,
I did a fresh install of ompd on base of dietpi distro to try your tip to my "getid3" problem.
But I wasn't successful with the basic fresh install. In the following, I describe the steps from the fresh install. 
My question is, is there a "problem" in ompd, or you think there is a "problem" in the dietpi distro?
What is confusing me, is that I use the same components (hardware/software) and steps before and I reached much further state; that brings me in the "issues" I reported before...!!!

Hardware: Raspberry Pi 2 Model B
Software: dietpi Image _DietPi_v6.8_RPi-ARMv6-Stretch.img_
                = V6.7 after Update = V6.9
Steps:
1. "blanks" a SD card (first formatted the SD card and then but the image on the SD card)
2. put the SD in the Rpi and start it
3. go to the basic installation and update process of the basic dietpi distro (including a reboot), which ends in this state:
  
![dietpi_ompd_fresh-install_001](https://user-images.githubusercontent.com/21111020/41823248-2c0e3266-77fd-11e8-9446-86c48ca184c3.png)

4. using the dietpi "config tool" to configurate a usb-dac as the sound output (including a reboot)
5. using the dietpi "software tool" to install "o!mpd", with this the following software parts was installed throught the dietpi distro:
5.1 alsa-utils check existence (was already installed while choosing the usb-dac)
5.2 webserver Lighttpd
5.3 MariaDB (instead of mysql, could this be a problem?)
5.4 php7.0 fpm (php-curl, php-gd, php-apcu, php-mcrypt, php-msql)
5.5 mpd (many libs...)
5.6 ompd
5.7 automated configuration from all that stuff through the dietpi distro; at the end this state:

![dietpi_ompd_fresh-install_002](https://user-images.githubusercontent.com/21111020/41823354-f688ef58-77fe-11e8-8362-7141533cb920.png)

5.8 including reboot

6. after the reboot I open a webbrowser (firefox) "http://dietpi/ompd"
7. first of all after the load of the page the following message was shown:
"Failed to Load MySQL server settings - When creating the database manaually also import the _sql/ompd_42.sql_ file manually." 
(I'm not sure if I got this message before, but if I tried to go further some things don't work as before; e.g. the database update don't work at all. But if I understand the message right, there is something wrong with a missing database setting file.):

![dietpi_ompd_fresh-install_003](https://user-images.githubusercontent.com/21111020/41823381-4912c370-77ff-11e8-97f7-5eacd6895a7d.png)

8. I ignored the message in the first step and logged into as admin and received the following state (please notice, that below the volume button there was only a "minus" = no value in percent. And if I tried to open the volume adjustment bar, there was no action/reaction):

![dietpi_ompd_fresh-install_004](https://user-images.githubusercontent.com/21111020/41823398-a3b3c7ac-77ff-11e8-9ded-1a17e9645952.png)

With this state, I logged out and shutdown the Rpi and await some tips... 

Sorry that I take your time on this (maybe) "stupid" questions!
Hope you can give me a light in the dark.
Thank you very much!
Frank

**Comment by ArturSierzant** [comment]
Looks like DB was created (O!MPD works correctly with MariaDB) - try to open any configuration option, like Player profile or Users - if it works it means that DB is created. You can also check it using phpMyAdmin or command line:
`mysql ompd -p`
and then enter password for DB - you'll find it in file `\ompd\include\config.inc.php` in variable called `$cfg['mysqli_password'] `. When you successfully connect to DB enter following command:
 `show tables from ompd;`
 and you should see something like this:
```mysql> show tables from ompd;
+-----------------+
| Tables_in_ompd  |
+-----------------+
| album           |
| album_id        |
| bitmap          |
| cache           |
| counter         |
| country         |
| favorite        |
| favoriteitem    |
| genre           |
| player          |
| random          |
| server          |
| session         |
| share_download  |
| share_stream    |
| track           |
| update_progress |
| user            |
+-----------------+
18 rows in set (0.00 sec)
```

As for 'minuses' in volume - it's probably caused by mixer setting in mpd config file. Check file /etc/mpd.conf (or wherever this file is located in DietPi), section `audio_output`, variable `mixer_type`. Try to set it to "hardware" or "software":
`mixer_type		"software"`
After that restart mpd service.

**Comment by ArturSierzant** [comment]
OK, let's leave problem with volume for now and let's try to solve problem with DB update. First of all try to turn on debugging: in `\ompd\include\config.inc.php` change `$cfg['debug']` to **true**. Then restart DB update - you will probably need to stop previous one: on config page scroll to _Update_ and click 3rd dot. Cancel sign should appear - click it:
![obraz](https://user-images.githubusercontent.com/22481059/41915230-8222fd0e-7955-11e8-9e8e-6732fa1f9a27.png)
Then start DB update again. Now update process will be logged to file `/ompd./tmp/update_log.txt`. When update crashes take a look at last lines of that file and past them here.

**Comment by ffatgit** [comment]
Hi,
it seems, that a solution is there!
The cause was the wrong row or steps of installation.
With this some configuration and entry were made in a wrong way,
There will be another comment with more details of the way of solution, in the next days...

Thank you for "staying with me so far".
Frank

**Comment by ffatgit** [comment]
Hello Artur,
today I had some time to dive into the ompd again. As I said, here some more informations why I struggled.
After fresh install of dietpi distro I forgot to install a file server as the first step. A file server e.g. samba is needed to work proper. I realized this after your support with the "log" file. Then I uninstall OMPD, reboot and installed the samba. Following up reinstall OMPD. But it seems that these steps something missing or setting wrong (NOT in OMPD!).
This took me a while to recognize. 
Then I go back to the start:
- format the SD card (in my notebook)
- write the dietpi image to the SD card (in my notebook)
- put the card to the raspberry pi
- start the device
- go through the main connfig of the dietpi distro
- update the distro to the lates version = V6.9
- then I installed FIRST the samba file server (through dietpi-software tool)
- activate samba as the file server (through dietpi-software config tool)
- reboot
- installation of OMPD and the mpd, mariaDB, php, ... (through dietpi-software tool)
- reboot
Then I was back at the point of the issue #68 [Question] file errors - invalid mpeg audio header (on a MP3 file) .

From my side this issue #70 is solved.

Thank you for your time and support!
