### ISSUE TITLE
[question] github labels

### ISSUE THREAD

**Issue by ffatgit** [ArturSierzant/OMPD#71]
Hello Artur,
let me ask you a general question:
Why it isn't possible to use/set the default labels from github (to issues)?
I searched for informations to this but there was no result that is clear to me.
Is the cause for this based in "right" matters?
In my opinion the labels are helpful for users and for the maintainer itself, too.

**Comment by ArturSierzant** [comment]
I think that only owner of repo can add labels - at least I have this possibility for OMPD. But I'm not sure - I don't know GitHub that well :(
