### ISSUE TITLE
[question]  which function has the internet ip tools

### ISSUE THREAD

**Issue by ffatgit** [ArturSierzant/OMPD#72]
Hello Artur;
which function has the internet ip tools section?

`//  +------------------------------------------------------------------------+
//  | Internet ip tools                                                      |
//  +------------------------------------------------------------------------+

$cfg['ip_tools']                    = 'http://www.infosniper.net/index.php?ip_address=%ip&map_source=1&overview_map=1&lang=1&map_type=1&zoom_level=5';
// $cfg['ip_tools']                    = 'http://ip-lookup.net/index.php?ip=%ip';`

**Comment by ArturSierzant** [comment]
This is from netjukebox. Try: `configuration -> online -> IP`. This make sense only when you allow access to O!MPD from Internet.
