### ISSUE TITLE
music directory generates a double slash and fails

### ISSUE THREAD

**Issue by catatung** [ArturSierzant/OMPD#74]
Hello,

I ran into this problem over a year ago and forgot what I did to fix it.  I can't believe nobody else has run into this problem since then and fixed it in the code.  After installing ompd and logging in for the first time (admin/admin), going to the database function update fails right out of the gate.  cfg['media_dir'] = /data/music/.  For example, if I specify a subdirectory for example "muse", I will get a "Failed to open directory" error because it is trying to access "/data/music//muse/whatever.mp3" --- if I use "Update all", it fails with /data/music//whatever.mp3.

I have tried removing the trailing slash from cfg['media_dir'], double quoting, and a bunch of things.
Ultimately if I remember correctly, it came down to code modification the last time, but it was so long ago I don't remember for fact.

Nobody else has seen this issue?  I can't find any mention of double slashes in my searching.

**Comment by catatung** [comment]
Update:  After messing around for awhile,  I did a chown -R mpd:mpd /data/* and a chmod -R 777 /data/* and now it works correctly.

My best guess without digging into code is that either ompd itself or an extension it uses tries adding a slash to the media_dir if a read error is found as a last ditch effort to make it work, and if that does not work then it forks out the error with the added slash showing.  Whether this guess is right or not, this should really be fixed - a permissions problem with the media dir should generate a permissions error message, not an ambiguous modified rendition (double slash) of what the media directory is configured to be.  Hopefully anybody else with this double slash issue will come across this post and know to try fixing permissions if a double slash error is being had.  Who knows, it might be myself in a couple years again, trying to remember how I got it to work the last time!

**Comment by ArturSierzant** [comment]
Thanks for that - just as you guess, there were a bug: in some cases additional `/` were added to the path of updated directory. I corrected this in f1a09c2. But in your case the problem was in dir permission - and should be clearly showed in info box:
![obraz](https://user-images.githubusercontent.com/22481059/42511276-b25a5fec-8451-11e8-823c-266d73623a23.png)
Did it show up in your case?

**Comment by catatung** [comment]
I honestly cannot remember....  There is good chance it did, and I disregarded the suggestion to check file permission because the path it displayed that it was trying to access was invalid, so a file permission/access error would have made sense to me based on that, so I was focused on fixing what file/path it was trying to access.  If there had been no readout of what it was attempting to access, I may have taken note of the permission suggestion and had a look there.  But with the invalid path displayed, I had 100% of my focus on that first.

If I get some time I will put a restrictive chmod on my music dir and confirm that the message does in fact appear...  But I am pretty sure it did.  I know an error appeared which displayed the (invalid) path/file it was trying to read.  I just don't remember with 100% certainty if the file permission suggestion was listed also.

Randy
