### ISSUE TITLE
Enhancement: Add support for composer tag

### ISSUE THREAD

**Issue by eikek** [ArturSierzant/OMPD#75]
Hi,

I really like O!MPD, so thank you very much for your effort! I have a little suggestion: since I mainly listen to classical music, I'd find it useful to have the composer tag in OPMD as well. Maybe it can get the same attention as the Artist tag in the library tab, so I could browse albums/songs by composer. What do you think?

**Comment by ArturSierzant** [comment]
Hi,
thank you for suggestion, I've already got it on my TODO list. I hope it will be done in next (not the nearest, which will be 1.04 but next, i.e. 1.05) version.

**Comment by eikek** [comment]
Ah nice that's great news. Thanks!

**Comment by ArturSierzant** [comment]
Done in 786a99f.
