### ISSUE TITLE
DR indexing

### ISSUE THREAD

**Issue by brendan-pike** [ArturSierzant/OMPD#77]
There seems to be a problem with the DR indexing. My DR view states I have Unknown DR of 2193 (38.9%) albums. But when I inspect they do have DR, if I manually update the single album I see that track DR gets added (sometimes) but not album DR.  I'm not sure how to debug though, let me know what I can do.
Thanks

**Comment by ArturSierzant** [comment]
DR order is as follows:
* for track:
['comments']['dynamic range'] -> ['tags']['id3v2']['text']['DYNAMIC RANGE']
* for album:
['comments']['album dynamic range'] -> ['tags']['id3v2']['text']['ALBUM DYNAMIC RANGE']

First part is valid for flac files, second for mp3 (at least it works for me - I use foobar2000 to add DR to files). Please check how it is written in your files - I guess your tags have different names.

**Comment by brendan-pike** [comment]
I tried to follow your tagging method since it already had partial support eariler, but I failed to note you wrote them into comments. 99% of my library is flac and my DR values are simply:
"album dynamic range" and "dynamic range".

I'm surprised any work for me since its not an array of comments?

**Comment by ArturSierzant** [comment]
By `['comments']` I mean section in getID3 analyse output, not tag `COMMENTS`. You can see how getID3 returns data by clicking 'File details' in track menu in album view or in Now Playing.  For flac files in my case it looks like this:
![obraz](https://user-images.githubusercontent.com/22481059/45172143-bae54100-b204-11e8-8ee7-a1abd72de47d.png)
So scripts reads ['comments']['dynamic range'] and ['comments']['album dynamic range'] and writes it into DB. Please check some of your files (which don't have DR in O!MPD) if they have these tags written properly.

**Comment by brendan-pike** [comment]
Thanks I understand now. Using the getID3 to examine I can confirm my tags are present and look the same as yours above.

**Comment by ArturSierzant** [comment]
There was a small bug in update procedure: when you did 'Update album' from album view, procedure updated only files that were added or modified since last update. In commit 0e19272 I fixed it, so now it really rescans all the files no matter they were added/modified or not.
Please try it for an album, which has DR tags and is not correctly indexed in O!MPD. If it works you can force update whole library: 
Config -> Update -> in 'Select directory' navigate to your media dir -> click 'Update this directory only'
This will rescan all files so it might take much time.

**Comment by brendan-pike** [comment]
I can cofirm this has fixed the issue, now unknown DR's is only 267 (4.7%) of my collection, which indeed do not hold DR values (mp3's mostly which I intend to delete). A full update is also taking a lot longer at 12mins currently.

**Comment by ArturSierzant** [comment]
Thanks for that.
