### ISSUE TITLE
Favorites/MPD's Playlists - option to sort the list

### ISSUE THREAD

**Issue by owl770** [ArturSierzant/OMPD#82]
Hi - thanks for a great app.

When you click on the Favorites link, you get a list of MPD's PLAYLISTS.

Is it possible to get the list sorted or is that an option you would consider adding?

**Comment by ArturSierzant** [comment]
Thanks for noticed this - I don't use MPD's playlists much, so I wasn't aware this list is not sorted. Of course I'll try to fix it.

**Comment by ArturSierzant** [comment]
Done in  c9aa908.
