### ISSUE TITLE
Loading MPD playlist via Favourites fails if playlist name contains a space

### ISSUE THREAD

**Issue by owl770** [ArturSierzant/OMPD#85]
Thanks for a great product. Really smooth.

On the favourites tab, when the MPD playlists are listed, if you try to add one that contains a space in the name, it fails with a message like:
![Screen Shot 2019-04-02 at 2 44 34 pm](https://user-images.githubusercontent.com/16440359/55374891-decbf380-5555-11e9-8884-d9affefadf27.png)
(my example is a playlist called "Easy Listening-01").

**Comment by ArturSierzant** [comment]
Thanks for that - it'll be fixed in next commit.

**Comment by owl770** [comment]
Hi - can we reopen this please?
On the Favorites tab, if you click the "Add to playlist" button it works as expected but if you click the "Play" button on a playlist that contains a space it fails...
![image](https://user-images.githubusercontent.com/16440359/74286174-53c5a780-4d7b-11ea-831c-a76a6824a4ff.png)

**Comment by ArturSierzant** [comment]
Oh, I see - previously I corrected it only for O!MPD's favorites, not for MPD's. I'll try to fix it today.

**Comment by ArturSierzant** [comment]
Done in 4c8f040. Thanks for reporting that.

Regards,
Artur
