### ISSUE TITLE
Getid3 dsf

### ISSUE THREAD

**Issue by marcbth** [ArturSierzant/OMPD#87]
Hallo Arthur,

For dsf files 

https://github.com/JamesHeinrich/getID3/blob/master/getid3/module.audio.dsf.php

Cliff

**Comment by ArturSierzant** [comment]
Hi Cliff,

thanks for that, but dsf files are already spupported in O!MPD. Problem is with dff files, which have non-standard way of storing metadata. Maybe that's why they still have no support in getID3 and hence in O!MPD.

Regards,
Artur

**Comment by marcbth** [comment]
Mandy thanks for your answer. 

I Hope TIDAL work Great. And Qobuz?
I have a Account for Qobuz. I can send you

Cliff

**Comment by ArturSierzant** [comment]
Unfortunately Qobuz isn't available in Poland, so I can't test it in any way.

**Comment by marcbth** [comment]
Its not a problem, you can use vpn. I can give you access.

qobuz may be important for rest outside poland.
Also have access for highresaudio incl. Api

hope can help you further.

cliff

**Comment by ArturSierzant** [comment]
Thanks for offering help - I'll remember that for the future. For now I'll focus on Tidal.

**Comment by mygalaxys9** [comment]
> Its not a problem, you can use vpn. I can give you access.
> 
> qobuz may be important for rest outside poland.
> Also have access for highresaudio incl. Api
> 
> hope can help you further.
> 
> cliff

highresaudio HI sir are you have highresaudio downloader like Qobuz or Tidal ?
