### ISSUE TITLE
File-details gives error

### ISSUE THREAD

**Issue by maartenlangeveld** [ArturSierzant/OMPD#89]
Hi Arthur,

Using latest O!MPD github master branche, I get the following error when requesting file-details (file does play however!) but cannot get the file info. I use Vivaldi browser (Chromium). Also using latest DietPi version (v6.24.1) with PHP 7.3.4-2 and lighttpd/1.4.53 (ssl).

It worked before. Don't know what caused the changed erratic behaviour. Php7.0 --> Php7.3 ? New lighttpd version ? O!MPD ?

_1st example_

Browser displays:
```
/mnt/user_data/Music/klassiek/Rachmaninov, Sergei Vassilievich/Piano Concertos 2 & 4 â Vladimir Ashkenazy â 1986/01 Piano Concerto No. 2 â I. Moderato.flac does not exist
```

Url in address bar (visual):
```
http://dietpi/ompd/getid3/demos/demo.browse.php?filename=/mnt/user_data/Music/klassiek%2FRachmaninov%2C) Sergei Vassilievich%2FPiano Concertos 2 %26 4 %E2%80%93 Vladimir Ashkenazy %E2%80%93 1986%2F01 Piano Concerto No. 2 %E2%80%93 I. Moderato.flac
```

Url in address bar (copy pasted):
```
http://dietpi/ompd/getid3/demos/demo.browse.php?filename=/mnt/user_data/Music/klassiek%2FRachmaninov%2C%20Sergei%20Vassilievich%2FPiano%20Concertos%202%20%26%204%20%E2%80%93%20Vladimir%20Ashkenazy%20%E2%80%93%201986%2F01%20Piano%20Concerto%20No.%202%20%E2%80%93%20I.%20Moderato.flac
```

_2nd example_

Browser output:
```
/mnt/user_data/Music/modern/Guru/Jazzmatazz Volume 1/01 Introduction.flac does not exist
```

Url in address bar (visual):
```
http://dietpi/ompd/getid3/demos/demo.browse.php?filename=/mnt/user_data/Music/modern%2FGuru%2FJazzmatazz+Volume+1%2F01+Introduction.flac
```

Url in address bar (copy pasted):
```
http://dietpi/ompd/getid3/demos/demo.browse.php?filename=/mnt/user_data/Music/modern%2FGuru%2FJazzmatazz+Volume+1%2F01+Introduction.flac
```

Luckily files are played normally :-)

**Comment by maartenlangeveld** [comment]
Addition: also cannot open directory in update anymore

> CONFIGURATION > UPDATE > UPDATE ONLY SELECTED DIRECTORY > Select directory:
> /mnt/user_data/Music/ > BROWSE

results in:
> DIR: /MNT/USER_DATA/MUSIC/
> SELECT THIS DIRECTORY
> Unable to open

**Comment by ArturSierzant** [comment]
Hi,
do you have this kind of problems with every file/location from your `/mnt/user_data/Music/` directory?
Now I'm also using DietPi v6.24.1, lighttpd/1.4.53 (ssl) and PHP 7.3.5 - and in my case everything works fine. 

It looks for me like files access problems: has user `www-data` access to your `Music` directory and its files?

**Comment by maartenlangeveld** [comment]
Hi Artur,

I did not have these problems till recently. Must say /mnt/user_data/Music/ is a symlink to another partition on same microSD card..

**Comment by ArturSierzant** [comment]
OK, I'm glad you found the solution.

Best regards,
Artur
