### ISSUE TITLE
indexation not working

### ISSUE THREAD

**Issue by daeavelwyn** [ArturSierzant/OMPD#9]
Hi,

First of all, thanks for your work ! I think O!MPD has a great future, it's a wonderfull player :)

But (of cours there is a "but"), I got into troubles with an annoying behaviour: I can't index my library.

I can create and update my database with mpd command line tools (and I got a 2.1Mo db file), but OMPD can"t populate the MySQL database, so, how can I get debug information about it ? 

It seems the indexation stop working after populates about 14 to 16 pages in MySQL db ( I made futher tests and looked at them throught phpmyadmin).

By comparison, I also tested ampache (because I wondered if the problems comes from OMPD or from mpd, or from php stuff), ampache indexation works very well, so I guess it's just a problem in the way OMPD creates/updates its own db, but I can't figure how to investigate more :-/

So If you can indicate me some tests I could do to verify that create/update mysqldb works I'd really appreciate.

**Comment by othmar52** [comment]
Hi,
I have the same problem. maybe enabling debug-mode helps in your case
@see #1

**Comment by ArturSierzant** [comment]
Hi,
as othmar52 advises, please turn on debug mode: edit `/include/config.inc.php`: find `$cfg['debug']` and change its value to **true**. More details you'll find here: #1 (3rd comment). 
Please let us know if you figured it out.

**Comment by othmar52** [comment]
Hi Artur,
Just to give you a status on my failed indexation. I am running into errors from time to time, where the indexing stops. The last error in detail was:
```
PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 61514097 bytes) in /path/to/ompd/getid3/getid3/getid3.php on line 1702
```
specific file was of type `*.m4a` with a size of `59.3 MB`

in the meantime i have extended `$cfg` where i can blacklist/skip problematic directories. Unfortunately it seems that O!MPD starts import from scratch every time without respecting the progress which already exists in database. So on each attempt it takes days to run into the next error.

Lets see if i have success. I'll keep you updated...

**Comment by ArturSierzant** [comment]
Thanks for your contribution, I'm looking forward next news :)

**Comment by othmar52** [comment]
Hi Artur,
Those memory-issues still exist within `update.php:fileInfo()`. i did some monitoring by extending the log with the result of `memory_get_usage()` within the loop. so i can see the constantly growing used memory.

i tried to `unset()` tons of php variables within the `fileInfo()`loop which resulted in the doubled amount of scanned files. but its far not enough.

next thing i am goining to try is to process smaller batches for beeing able to free mysql memory usage.

btw netjukebox's update stuff is the most horrible peace of code i've ever seen. too bad it affects O!MPD that much.

**Comment by ArturSierzant** [comment]
I've merged othmar52's pull request with improvements of update procedure. 
daeavelwyn, could you please check if this fix your problem?

**Comment by ArturSierzant** [comment]
Because there were many improvements of update procedure since this issue was reported, I assume that problem is solved and I'm closing that issue.
