### ISSUE TITLE
Tidal plugin

### ISSUE THREAD

**Issue by marcbth** [ArturSierzant/OMPD#90]
Hallo Arthur,
I have debian buster installed with mariadb and mpd 0.21.9
when i search in ompd he finds everything in tidal and i can put it in the playlist. but:
he does not play a song.

can you help me?

Thank you very much

cliff

**Comment by marcbth** [comment]
in the mpd.log

un 01 21:22 : exception: avformat_open_input() failed: Invalid data found when$
Jun 01 21:22 : exception: Error from Tidal: Asset is not ready for playback
Jun 01 21:22 : player: played "tidal://track/51771417"
Jun 01 21:22 : client: [907] opened from 127.0.0.1:46094
Jun 01 21:22 : client: [908] opened from 127.0.0.1:46096
Jun 01 21:22 : client: [907] closed
Jun 01 21:22 : client: [909] opened from 127.0.0.1:46098
Jun 01 21:22 : client: [908] closed
Jun 01 21:22 : client: [909] closed
Jun 01 21:22 : client: [910] opened from 127.0.0.1:46100

**Comment by ArturSierzant** [comment]
Hello Cliff,

I've just switched to RasPi3B+ and have similar issiues:
`avformat_open_input() failed: Invalid data found when processing input`
and
`CURL failed: Operation timed out after 10110 milliseconds with 0 out of 0 bytes received` 

I just took out SD card from old RasPi3B and put it into new one (RasPi3B+). Since I had a backup SD card of my old RasPi3B, I put it into my old RasPi3B. And strange things started: on old RasPi3B Tidal worked OK, but on new one it didn't - I had errors listed above. So I switched SD cards between RasPi - this time Tidal played on both RasPi. So I switched cards once again: new RasPi3B+ has now card that was oryginally in RasPi3B and old RasPi3B has backup card. And this time Tidal plays on both RasPi. I can't explain that...

Your problem looks like problem with mpd - O!MPD just adds to mpd's playlist items like `tidal://track/147895` - the rest is handled by mpd (BTW I use mpd 0.21.5). This particular track comes from [Huey Lewis & The News 'Sports'](https://listen.tidal.com/album/147894) - it's the first track titled 'The Heart Of Rock And Roll'. Try to play it - it plays in my case. Try also play other albums - if problem will still be active then try to report it on [mpd GitHub page](https://github.com/MusicPlayerDaemon/MPD/issues).
Or maybe your case is the result of ['TIDAL deprecates username/password login for oAuth'](https://github.com/MusicPlayerDaemon/MPD/issues/545)?

Anyway, here, in Poland Tidal still plays on mpd.

Regards,
Artur

**Comment by marcbth** [comment]
Hello Artur,

many thanks for your response.

Yesterday I switched from debian stretch to debian buster.

at strech I use currently upmpdcli with tidal plugin (check it out please) and it works without problems via hhtps stream. is also displayed in ompd and then in mpd / ncmpc and played.

Do you think that it is possible to make a menu point where you can see the tidal structure (my playlist, new albums etc)?

at debian buster is at the moment php 7.3 as standard. maybe that's the reason?

It is strange.

Oh yes, use a "normal" pc with debian amd64 no raspberry.

Hope we come up with a solution.

Cliff

**Comment by marcbth** [comment]
Hello Artur,

news:

tidal: Login successful, session=8f186af2-f3fe-4175-9428-0a1657cea9ae
exception: Failed to decode tidal://track/75206893
player: played "tidal://track/75206893"
exception: Failed to decode tidal://track/75206893
client: [0] command returned 2

**Comment by marcbth** [comment]
tidal: Login successful, session=3dcd84b6-4772-4e78-9720-6f506eb80461
decoder_thread: probing plugin ffmpeg
exception: avformat_open_input() failed: Invalid data found when processing input

**Comment by ArturSierzant** [comment]
Really looks like problem with mpd. I've just installed buster on my RasPi3B+ and Tidal plays fine. I don't think it's somehow related with php7.3.

As for your questions about Tidal structure: I think it's possible. I'll try to add more Tidal's features in near future. Now I'd like to focus on finishing what is already added to O!MPD.

**Comment by marcbth** [comment]
Hallo Artur,

look at

https://github.com/MusicPlayerDaemon/MPD/issues/545

**Comment by marcbth** [comment]
can you add the tidal file for a http stream for mpd?

like: https://tidal.....

**Comment by marcbth** [comment]
upmpdcli have this. 
when i play a tidal file from upmpdcli i have ouput n mpd https://tidal.....
an i can play this

**Comment by ArturSierzant** [comment]
Can you give the full url?

**Comment by marcbth** [comment]
https://www.lesbonscomptes.com/upmpdcli/downloads.html
https://opensourceprojects.eu/p/upmpdcli/code/ci/5fbea55f973ed222cd3e635440500025626fd074/tree/

i hope, this helps

**Comment by marcbth** [comment]
volumio have an upnp browser plugin

**Comment by marcbth** [comment]
https://www.lesbonscomptes.com/upmpdcli/upmpdcli-manual.html#plgmicrohttpport

**Comment by ArturSierzant** [comment]
I meant full url of a Tidal song :)

I red MusicPlayerDaemon/MPD#545 - looks like I, unfortunately, had a good premonition... And Tidal works for me because:
>  The old API tokens issued earlier are still working.

I got my token about 2 months ago. If you really want, you can find old tokens in the Internet and try it (e.g. [here)](https://github.com/tamland/python-tidal/blob/master/tidalapi/__init__.py)

**Comment by marcbth** [comment]
sorry, my mistake.
I can give you a url tomorrow morning.

my system needs to be reset.

hope that's enough.

I've always used upmpdcli with linn kazoo. but wanted to change and leave the whole upnp branch out.

've got the songs displayed in ompd playlist.

I think your solution is very elegant and would like to install it in my music server.

if mpd does not directly more, it is perhaps a possibility via http stream

**Comment by marcbth** [comment]
process command "addid "http://192.168.178.47:49149/tidal/track?version=1&trackId=104710007" "0""
client: [0] command returned 0
client: [0] process command "addtagid "1" "Artist" "Khotin""
client: [0] command returned 0
client: [0] process command "addtagid "1" "Album" "Beautiful You""
client: [0] command returned 0
client: [0] process command "addtagid "1" "Title" "Vacation""
client: [0] command returned 0
client: [0] process command "addtagid "1" "Track" """
client: [0] command returned 0
client: [0] process command "addtagid "1" "Comment" "client=upmpdcli;""
client: [0] command returned 0
client: [0] process command "status"
client: [0] command returned 0
client: [0] process command "status"
client: [0] command returned 0
client: [0] process command "playlistinfo"
client: [0] command returned 0
client: [0] process command "playlistid "1""
client: [0] command returned 0
client: [0] process command "playid "1""
playlist: play 0:"http://192.168.178.47:49149/tidal/track?version=1&trackId=104710007"
client: [0] command returned 0
client: [0] process command "status"
client: [0] command returned 0
client: [0] process command "currentsong"
client: [0] command returned 0
client: [0] process command "playlistinfo "1""
client: [0] command returned 0
client: [0] process command "status"
client: [0] command returned 0
client: [0] process command "currentsong"
client: [0] command returned 0
client: [0] process command "playlistinfo "1""
client: [0] command returned 0
decoder_thread: probing plugin flac
decoder: audio_format=44100:16:2, seekable=true
alsa_output: opened hw:1,0 type=HW
alsa_output: buffer: size=16..131072 time=362..2972155
alsa_output: period: size=8..65536 time=181..1486078
alsa_output: default period_time = buffer_time/4 = 500000/4 = 125000
alsa_output: format=S32_LE (Signed 32 bit Little Endian)
alsa_output: buffer_size=22050 period_size=5513
output: opened plugin=alsa name="DAC" audio_format=44100:32:2
output: converting in=44100:16:2 -> f=44100:16:2 -> out=44100:32:2
exception: Failed to open mixer for 'DAC': no such mixer control: PCM

**Comment by ArturSierzant** [comment]
I've installed `upmpdcli-tidal` and indeed it's working. I added support for it in commit 4261380. You need to do one setting in `config.inc.php`: change `$cfg['upmpdcli_tidal']`. In your case it should look like this:

`$cfg['upmpdcli_tidal'] = "http://192.168.178.47:49149/tidal/track?version=1&trackId=";`

Please let me know if this works. In my case, playing via upmpdcli seems to be more stable than using mpd pluugin.

**Comment by marcbth** [comment]
hello Artur,

it does not work as it should.

1 search does not work (nothing is displayed)
2 now playing = track tidal_id 103581530

no artist, track

On the other hand, if I take mconnect and apply my tidal access he shows me artist etc.

no cover for both

cliff

**Comment by marcbth** [comment]
at the now playing page, he shows the track name at the top, still formatted incorrectly.

no artist album etc

**Comment by marcbth** [comment]
before you inserted the new one, I could select a title via linn kazoo, mconnect etc and ompd showed me everything correctly (cover was missing).

it comes at the moment synonymous not a mistake, that ompd in the search has found nothing in tidal (the part is missing entirely) in native integration, he showed me the tidal search results and they were selectable.

**Comment by marcbth** [comment]
ncmpc displays the artist and title

**Comment by ArturSierzant** [comment]
Strange, the search part was not modified it this commit... Do you still have Tidal part in `config.inc.php` (tidal_username/tidal_password/tidal_token) properly defined?

**Comment by marcbth** [comment]
no, the part is empty

**Comment by ArturSierzant** [comment]
It must be filled to Tidal work properly.

**Comment by marcbth** [comment]
I noticed right now.

the problem is the token.

which should I take now? from the api? he does not work

Error in execution Python script.
Error message:

Traceback (most recent call last), File "/var/www/ompd/tidalapi/tidalSearch.py", line 20, in, session.login (user, password, token), File "/ var / www / ompd / tidalapi / tidalapi / __ init__.py ", line 74, in login, r.raise_for_status (), File" /usr/lib/python2.7/dist-packages/requests/models.py ", line 893, in raise_for_status, raise HTTPError (http_error_msg, response = self), requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://api.tidalhifi.com/v1/login/username?token=kgsOOmYk3zShYrNP

**Comment by ArturSierzant** [comment]
I checked this token and it works for my account. Have you entered `tidal_username` and `tidal_password`?

**Comment by marcbth** [comment]
it works!!

wonderful!!!

many thanks for your effort.
How can I thank you?


i will insert qobuz as well as your model tomorrow.

with upmpdcli-qobuz.

I still have upmpdcli-highresaudio if you are interested.

do you think that it is difficult to integrate a menu item where tidal's structure is displayed? as with upmpdcli.
because of its own tidal playlist etc

**Comment by ArturSierzant** [comment]
You welcome :)
Qobuz will surely not work with O!MPD - it has different API. Besides in Poland Qobuz is not available, so I can't even test it.
I'll try to add more Tidal's menus in near future. I don't know yet what will be possible, but I think that some of them for sure.
But I have some doubts about Tidal - if they remove possibility of logging using user/password/token, then all this work will be useless...

**Comment by marcbth** [comment]
I try to do the same with the upmpdcli-qobuz plugin.

I can give you an account. maybe he works in poland. otherwise by vpn.

I have created a fork and will write my changes in there (cd play, server settings (wlan, tidal access data, nas connection etc, qobuz, modified surface)). synonymous have a lot removed in the settings. a little cleaner and more intended for the enduser

maybe there is something for you too.

as a suggestion: in the main menu liberary, streaming, now playing

**Comment by marcbth** [comment]
is it still possible to insert the little playlist in footer in now playing?

if the playlist gets long, it is very inconvenient always to go up and select the next song. In the Liberary view it is there.

I hope I do not nerve too much

**Comment by ArturSierzant** [comment]
It is possible to add 'mini-player' to 'Now Playing', but it requires some modifications in code. Most of them must be done in file `playlist-mini.php`, which uses a lot of code from `playlist.php` (main file of 'Now Playing'): function names, DOM objects names, etc. So you'd have to do quite a lot of code refactoring.  Also `skin/[skin_name]/template.footer.php` needs to be modified (remove `NJB_SCRIPT != 'playlist.php' && ` from line 151). 

And don't worry about making me nervous :) If I'm not answering it only means that I don't have enough time.
