### ISSUE TITLE
Miniplayer panel broken in v1.04

### ISSUE THREAD

**Issue by bamyasi** [ArturSierzant/OMPD#91]
I am having a strange looking additional panel displayed at the bottom of O!MPD Library page. I suppose this is the miniplayer interface but all it shows are blank disk icon and some text next to it, e.g.:

3/30.
by from

3/30 looks like the number of currently played track / total number of tracks in the playlist but the 'by from' part I assume should be listing track / artist / album name except it does not work since all fields are constantly blank. And no album's icon is shown either.

I have tried to locate the miniplayer section in the include/config.local.inc.php file as suggested in documentation but was unable to find anything related. Miniplayer configuration is also missing from the documentation on the O!MPD web site.

**Comment by ArturSierzant** [comment]
Thanks for feedback. Miniplayer section is defined in [/include/config.inc.php](https://github.com/ArturSierzant/OMPD/blob/master/include/config.inc.php#L188) as `$cfg['show_miniplayer']`. It's default value is `true`, when you set it to `false` miniplayer should hide. When `$cfg['show_miniplayer']` is not defined at all, miniplayer also should be hidden. 

Have you just installed v1.04 (where from? GitHub/web site) or had miniplayer worked before and it just stopped? 

Regards,
Artur

**Comment by bamyasi** [comment]
Hi Artur,

Thank you very much for the prompt response.

> Thanks for feedback. Miniplayer section is defined in [/include/config.inc.php](https://github.com/ArturSierzant/OMPD/blob/master/include/config.inc.php#L188) as `$cfg['show_miniplayer']`. It's default value is `true`, when you set it to `false` miniplayer should hide. When `$cfg['show_miniplayer']` is not defined at all, miniplayer also should be hidden.

It turned out my installation was still using include/config.local.inc.php file from previous version, which was overwriting updated configuration in include/config.inc.php. I have fixed that but it did not fix the miniplayer issue. It is still displayed empty.

> Have you just installed v1.04 (where from? GitHub/web site) or had miniplayer worked before and it just stopped?

I have O!MPD installed as part of the DietPi OS installation on my Allo Sparky SBC with USBridge HAT. O!MPD was upgraded automatically during recent DietPi upgrade to v6.25.3. As far as I can see from a few files I have checked, which are all identical to the corresponding GitHub master versions, the upgrade script pulled this version from GitHub. It says 'O!MPD 1.04' in the banner at the bottom of the web pages and that's what it has stored in the include/initialize.inc.php file, both on my SBC and at GitHub.

Note that it would still display this broken miniplayer panel even  when it was still using old include/config.local.inc.php file which had no show_miniplayer setting in it, contrary to expected behavior you mentioned.

I have disabled miniplayer in the configuration and it worked as expected: miniplayer panel is no longer shown.

**Comment by bamyasi** [comment]
I am attaching here a screenshot from my installation with the broken miniplayer panel shown.
![ompd_miniplayer_bug](https://user-images.githubusercontent.com/16567328/60760742-931f5f00-a008-11e9-9170-982bd1f80235.jpg)

**Comment by ArturSierzant** [comment]
Please try to clear your web browser cache. If it won't help try to run debugging tool in Firefox (F12), switch to Console menu and try to find any errors.

**Comment by bamyasi** [comment]
Hi Artur,

Clearing browser cache does not help, as well as switching between several different browsers on my Ubunu desktop (Chrome, Chromium, Firefox) or on my Android phone (Firefox Mobile, Chrome, Samsung Internet Browser). All browsers display the same empty panel all the time.

When miniplayer is enabled in configuration I can see the following errors in the Web Console in the Firefox:

===QUOTE===
Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user’s experience. For more help http://xhr.spec.whatwg.org/ jquery-1.11.3.min.js:5:25379
miniplayerW: 1280 arts.functions.js:343:10
art: <a href="index.php?action=view2&order=year&sort=asc&artist="></a> index.php:1275:10
8884 index.php:891:11
isplaying:3; idx: 0 index.php:1169:11
art: <a href="index.php?action=view2&order=year&sort=asc&artist="></a> index.php:1275:10
art: <a href="index.php?action=view2&order=year&sort=asc&artist="></a> index.php:1275:10
art: <a href="index.php?action=view2&order=year&sort=asc&artist="></a> index.php:1275:10
art: <a href="index.php?action=view2&order=year&sort=asc&artist="></a> index.php:1275:10
art: <a href="index.php?action=view2&order=year&sort=asc&artist="></a> index.php:1275:10
art: <a href="index.php?action=view2&order=year&sort=asc&artist="></a> index.php:1275:10
art: <a href="index.php?action=view2&order=year&sort=asc&artist="></a> index.php:1275:10
art: <a href="index.php?action=view2&order=year&sort=asc&artist="></a> index.php:1275:10
<...>
===END QUOTE===

The last string keeps popping constantly.

**Comment by bamyasi** [comment]
Sorry, clicked the wrong button accidentally.

**Comment by ArturSierzant** [comment]
Unfortunately, I can't reproduce it in my system. Maybe you could download O!MPD from GitHub and give it a try.
Maybe tomorrow I'll try to install DietPi and see what's going on.

**Comment by bamyasi** [comment]
Could it be because of the PHP 7.3? Version included with the DietPi was upgraded to php7.3 during the system upgrade, at the same time with the O!MPD. However, my Ubuntu 19.04 desktop still sticks to PHP 7.2. I will try installing O!MPD from GitHub on it and report results. At the moment, I am using Cantata player as MPD client on my KDE desktop, which works great.

**Comment by ArturSierzant** [comment]
I've just installed DietPi. After initial updating and installing O!MPD (indeed downloaded from GitHub - latest commit) all works OK... It runs at PHP 7.3, lighttpd and mariadb. I really don't know why it's not working in your case.

**Comment by bamyasi** [comment]
Same software here except I've upgraded my DietPi several times since the initial installation in December last year, so it is not a fresh install. Could it be due to some permissions issue? Can you check what are the permissions for 'anonymous' user on your system? Mine has only Media checked, everything else is unchecked.

**Comment by bamyasi** [comment]
Discovered one more hint while attempting to debug this problem. The following appears in the /var/log/lighttpd/error.log file when show_miniplayer=true and the library tab is open in the browser:

`(mod_fastcgi.c.2543) FastCGI-stderr: PHP message: PHP Warning:  strpos(): Empty needle in /var/www/ompd/include/library.inc.php on line 748`

The error is repeated indefinitely. When I set show_miniplayer=false then this error is **not** printed.

Looking into ompd/include/library.inc.php, the code in question seems related to Tidal support. I do not have any Tidal support installed or configured here.

**Comment by ArturSierzant** [comment]
Looks like miniplayer can't get proper indexes from playlist. Let's try find why. Try this: in Firefox press `Ctrl+Shift+E` - you'll see network panel from debugging tool. Now click `Library` menu - network panel should fill up with network requests. Find among them calls for:
1. `ajax-playlist-mini.php`
2. `play.php?action=playlistTrack&track_id=[...]`

Click on them and paste here values of:
- Headers -> Request URL
- Response -> Preview (or JSON)

> Can you check what are the permissions for 'anonymous' user on your system? 

Anonymous by default is only allowed to see Media. But you logged in as admin, right?

**Comment by bamyasi** [comment]
Looks like all payload is missing or null but the network debugging logs do not show why:

ajax-playlist-mini.php:

Headers:
`Request URL:http://dietpi.local/ompd/ajax-playlist-mini.php
Request method: GET
Remote address: 192.168.1.140:80
Status code: 302
Version:HTTP/1.1
Referrer Policy: no-referrer-when-downgrade`
Response:
`No response available for this request`

play.php?action=playlistTrack&track_id=...

Headers:
`Request URL:http://dietpi.local/ompd/play.php?action=playlistTrack&track_id=undefined&menu=playlist&ajax=1
Request method:GET
Remote address: 192.168.1.140:80
Status code: 200
Version:HTTP/1.1
Referrer Policy:no-referrer-when-downgrade`
Response:
JSON:
`track_artist | […]
0 |  
track_artist_all | null
track_artist_url | […]
0 |  
track_artist_url_all |  
track_composer | […]
0 |  
track_composer_all | null
track_composer_url | […]
0 |  
track_composer_url_all |  
title |  
album |  
by |  
image_id |  
album_id |  
year |  
genres | []
audio_dataformat |  
audio_bits_per_sample |  
audio_sample_rate |  
audio_profile |  
number | .
miliseconds |  
other_track_version | false
comment |  
track_id |  
relative_file |  
inFavorite | false
onBlacklist | false
dr |  
album_dr |  
title_core | null`
Payload:
`{"album_artist":"","track_artist":[""],"track_artist_all":null,"track_artist_url":[""],"track_artist_url_all":"","track_composer":[""],"track_composer_all":null,"track_composer_url":[""],"track_composer_url_all":"","title":"","album":"","by":"","image_id":"","album_id":"","year":"","genres":[],"audio_dataformat":"","audio_bits_per_sample":"","audio_sample_rate":"","audio_profile":"","number":". ","miliseconds":"","other_track_version":false,"comment":"","track_id":"","relative_file":"","inFavorite":false,"onBlacklist":false,"dr":"","album_dr":"","title_core":null}`

**Comment by bamyasi** [comment]
Yes I am normally logged as admin when using the player. I was just wondering what's the role was for this Anonymous user.

**Comment by ArturSierzant** [comment]
Result of `ajax-playlist-mini.php` is empty and it shouldn't be. Please try to add a new player: Config -> Player profile -> Add new. Enter any name (like 'test' or something like this), as `Player host` enter the same address as for currently used MPD (probably 127.0.0.1) and then Save. On the players list click newly added one to make it active. Under note icon in navigation bar you should see name of active player. Then switch to Library and see how miniplayer looks. If it's still corrupted, click note icon and then click the button with new player. Let's see what happens....

**Comment by bamyasi** [comment]
It worked! I have created a new player with the same host address (127.0.0.1), switched to it in the web interface and now I have fully occupied miniplayer panel with album art, title, track name, artist, etc. Thanks so much for your persistence and patience in helping me out with fixing this issue!

I have one question. There is now buttons to synchronize / copy / add shown right below select player buttons (under the note icon). What do they do and should I try one of them? Which one?

**Comment by bamyasi** [comment]
Ok, I figured this last one out: it's for the playlist synchronization. Interestingly, my current playlist has been already copied to the newly created player automatically. Very cool!

**Comment by ArturSierzant** [comment]
Yes, that's useful when you have more than 1 MPD player. Then you can sync/copy/add playlists between them.
