### ISSUE TITLE
Improve image error handling

### ISSUE THREAD

**Issue by brendan-pike** [ArturSierzant/OMPD#92]
While cleaning my collection I've found an annoying bug with images where an image that is not accepted during index needs to be removed and re-added to appear.

For example if I had an image called cover.jpg but the permissions were incorrect so that nginx was unable to read it on indexing it fails naturally.  If I then correct the file permissions and reindex the album the image will still not appear.  I am forced to do the following:
1. Correct image permission issue
2. Move the image out of the directory or rename to cover.jpg.tmp
3. Reindex the album
4. Move the file back into the directory (or rename back to cover.jpg)
5. Reindex the album

Expected behavior is that it should reindex the image without the mucking around.

**Comment by ArturSierzant** [comment]
Done in commit 10e09ac.
