### ISSUE TITLE
Album database destroyed

### ISSUE THREAD

**Issue by brendan-pike** [ArturSierzant/OMPD#94]
I tihnk I found a new nasty issue.  I have around 2500 albums, I did an "update all" after adding a few new albums, while this was happening I was listening to an album and noticed another cover image issue, I re-indexed that album and now I only have 1 album in my collection. So I'm guessing the interrupted indexing was fatal.

**Comment by ArturSierzant** [comment]
Sorry to hear that - I hope you have DB backup. I tried to reproduce this, but no luck. No matter in what stage of update (Structure & image, File info, etc.) I tried to 'Update album', I was always redirected to 'Configuration -> Update' with running 'update all' process started before - just like it should work.

**Comment by brendan-pike** [comment]
I thought I could reproduce it, but I was wrong.   None the less I'll comment and say I continue to loose my entire album database one in awhile. Probably since I constantly do renaming and cleaning of albums / artists. So while I can't yet give a resproducable error, I am wondering how its possible to loose all albums when something is glitching.  It makes me think there is a sql select update command that somehow becomes * global in its reference.

Sigh... I guess having a backup / restore function of the database would be useful.

**Comment by brendan-pike** [comment]
No action required yet, but its just happened again, however this time my system crashed during an album refresh. So I'll try and replicate this when I get a chance soon.

**Comment by tomchiverton** [comment]
It's been two years, nobody ever reproduced, thing we can close :)

**Comment by ArturSierzant** [comment]
That's right.
