### ISSUE TITLE
Is it possible to 'auto login' or disable the requirement to login?

### ISSUE THREAD

**Issue by owl770** [ArturSierzant/OMPD#95]
Hi - thanks for a great project. Works very well.
When you first connect to OMPD, you are prompted to login (as either anonymous, admin or another user). Is there a way to automatically provide these credentials or to disable the requirement to login? I want to be able to connect to OMPD and not be prompted to login. Thanks.

**Comment by ArturSierzant** [comment]
Hi, 
there is a kind of walk-around solution: in `include/config.inc.php` change:
* `$cfg['anonymous_user']` to `admin`
*  you can also increase `$cfg['session_lifetime']` 

Then logout and login again - this time `admin` will be default username, just click `login` and you're done (no need to enter password). Session will be remembered for time set in `$cfg['session_lifetime']` 

Regards,
Artur

**Comment by owl770** [comment]
Thanks. Not a perfect solution but will work for now. Thanks for the quick response.
