### ISSUE TITLE
Login always shows error

### ISSUE THREAD

**Issue by brendan-pike** [ArturSierzant/OMPD#96]
Everytime I login with admin I am shown an error alert that says:
"Login failed
netjukebox requires cookies to login.
Enable cookies in your browser and try again."

The login did succed however because if I click any link it works fine.

**Comment by marcbth** [comment]
I have the same problem

**Comment by ArturSierzant** [comment]
I think that cleaning cookies from browser should help. 
Generally speaking, logging procedure requires some changes...

**Comment by brendan-pike** [comment]
Just a long overdue follow up on this.  I'm quite certain there is some sort of login problem occurring still.  I've tried clearing cache to no avail. The same error even occurs on a cleanly installed OS.

That aside I'd like to ask for a semi-related feature. That is to enabled 'auto' user logins on certain accounts. Specifically I've built my daughter a music player. I used a raspberrypi 4 with a 7" touch screen.  I actually installed installed Moode Audio on it and then changed the chromium browser to launch my network installation of OMPD instead of the local moode GUI.  I then add her moode player as a mpd server so it plays back to her device.  It works very well in testing so far.  But the catch is it requires her login, I would like to be able to have her auto-logged in on boot. Perhaps with the url, eg. http://x.x.x.x/ompd/login?username=chris&password=xyz This could be one method.

Also, Artur have you thought about adding a forum to http://ompd.pl or something we could discuss things more generally?

**Comment by brendan-pike** [comment]
I checked out the latest netjukebox code of json.php it isn't wildly different.  Seems they've cleaned it up a bit and added some security features, perhaps its easier to pull in those changes.  If you give me some basic tips I could try and debug it.

**Comment by marcbth** [comment]
> I checked out the latest netjukebox code of json.php it isn't wildly different. Seems they've cleaned it up a bit and added some security features, perhaps its easier to pull in those changes. If you give me some basic tips I could try and debug it.

Hello Brendan,

Let's all together try to improve ompd. can only offer my help (see my fork) ompd is at the moment unfortunately only of artur supervised. Hope we can change that.

cliff

**Comment by marcbth** [comment]
hello brendan,

Let us try together.
I sit close to the consumer or user. And unfortunately we are computer nerds always blind to the usibilty.
have access for moqups for multiple participants, because i would like to provide.

cliff

**Comment by ArturSierzant** [comment]
In 8eeffe1 I changed a little bit setting cookie in log-in procedure. Hope it will help with errors in logging.

**Comment by ArturSierzant** [comment]
I'm afraid changes in 8eeffe1 didn't help... So in 2f80962 I simplified the login procedure. Now it should work more stable (deleting cookies may be required at the beginning). 

And @brendan-pike  - as you suggested I added `login.php`. Usage:

`login.php?username=[user name]&password=[password]&player=[player name as defined in 'Player profile']`

e.g:

`login.php?username=admin&password=admin&player=bedroom`

When `played` is omitted, default one will be used. Thanks for that - good idea. It encouraged me to get into login procedure more deeply.

I also added default username/password that will be entered into login form - see `config.inc.php`.

Please let me know if that helped for logging issue.

**Comment by brendan-pike** [comment]
Hi Artur, I just tested and its working great.  The url login is much appreciated, it makes for a smooth integration on the rpi touchscreen. I'm running MoodeAudio on it, but have altered the chromium launch to point at our local install of OMPD.  Its seamless :)
