### ISSUE TITLE
After adding a youtube stream 'Now Playing' page is not refreshed

### ISSUE THREAD

**Issue by maartenlangeveld** [ArturSierzant/OMPD#99]
After adding a youtube stream 'Now Playing' page is not refreshed.

**Comment by maartenlangeveld** [comment]
When adding a youtube stream 'Now Playing' page is not refreshed.

**Comment by ArturSierzant** [comment]
When you enter YT address and click `+ ADD`, does the `+` sign change to red `!`?  Did it work earlier?

**Comment by maartenlangeveld** [comment]
Hi Artur,

No, just wheel turning, after approx. 15 sec. youtube video's audio start to play, that works fine but screen is not refreshed still showing empty playlist, player and file info is ot shown, manually refresh page does solve te problem but I expected to automatically have page refresghes shwoing playlist and player as soon as yt audio stream starts playing.


Thanks, Maarten

**Comment by ArturSierzant** [comment]
OK, I see it. I'll try to fix it.

**Comment by ArturSierzant** [comment]
Done in 30554fb

**Comment by maartenlangeveld** [comment]
@ArturSierzant 

Thanks, problem solved but new problem introduced. Now the screen is refreshed but the video's won't play!

**Comment by maartenlangeveld** [comment]
Thanks, problem solved but new problem introduced. Now the screen is refreshed but the video's won't play!

Op Tue, 20 Aug 2019 20:18:15 +0200 schreef Artur Sierżant <notifications@github.com>:


OK, I see it. I'll try to fix it.

**Comment by ArturSierzant** [comment]
Video is not supported... only audio from video. Does this problem concern audio? I tested it, and had no problems with playing audio from YT (besides this part was not changed in this commit).

**Comment by maartenlangeveld** [comment]
I meant the audiopart does not play anymore after applying the fix. Thanks
________________________________

**Comment by ArturSierzant** [comment]
Just wanted to be sure. So when you paste YT link, it appears on playlist, but is not played even if you click `Play` button? Maybe try to update youtube-dl: `youtube-dl -U`

**Comment by maartenlangeveld** [comment]
Hello Arthur,

Thanks, apparently it works not with all yt content... So must be yt dl issue and not OMPD. My apologies.

Maarten


Op Mon, 26 Aug 2019 11:28:23 +0200 schreef Artur Sierżant <notifications@github.com>:


Just wanted to be sure. So when you paste YT link, it appears on playlist, but is not played even if you click Play button? Maybe try to update youtube-dl: youtube-dl -U

**Comment by ArturSierzant** [comment]
No need to apologize :) Thanks to you O!MPD now works better.
